/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_management;

import com.mxrck.autocompleter.TextAutoCompleter;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Tài
 */
public class HoaDon extends javax.swing.JInternalFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form tableSuaThongTin
     */
    public HoaDon() {
        initComponents();
        conn = JavaConnect.ConnectDB();
        updateTableHoaDonNhap();
        fillComboMaThuoc();
        fillComboMaNhaCungCapNhap();
        fillComboMaKhachHangXuat();
    }

    private void updateTableHoaDonNhap() {

        String sql = "select * from TableHDNhap";
        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            jTableHDNhap.setModel(DbUtils.resultSetToTableModel(rs));
            pst.close();
            rs.close();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }

    }

    private void updateTableHoaDonXuat() {

        String sql = "select * from TableHDxuat";
        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            jTableHDXuat.setModel(DbUtils.resultSetToTableModel(rs));
            pst.close();
            rs.close();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        buttonGroupHDXuat = new javax.swing.ButtonGroup();
        buttonGroupHDNhap = new javax.swing.ButtonGroup();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHDNhap = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btnInNhap = new javax.swing.JButton();
        btnThemNhap = new javax.swing.JButton();
        btnXoaNhap = new javax.swing.JButton();
        btnSuaNhap = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        txtSTTNhap = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        txtMaHDNhap = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jComboBoxMaNhaCungCapNhap = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxMaThuocNhap = new javax.swing.JComboBox();
        jPanel10 = new javax.swing.JPanel();
        txtSoLuongNhap = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtGiaNhap = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtThanhTienNhap = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        txtThanhToanNhap = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        dateChooserNhap = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel18 = new javax.swing.JPanel();
        jRadioButtonMaThuocNhap = new javax.swing.JRadioButton();
        jRadioButtonMaHDNhap = new javax.swing.JRadioButton();
        jRadioButtonNhaCungCapNhap = new javax.swing.JRadioButton();
        jRadioButtonThanhTienNhap = new javax.swing.JRadioButton();
        txtTimKiemHDNhap = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableHDXuat = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        dateChooserXuat = new com.toedter.calendar.JDateChooser();
        txtThanhToanXuat = new javax.swing.JTextField();
        txtThanhTienXuat = new javax.swing.JTextField();
        txtGiaXuat = new javax.swing.JTextField();
        txtSoLuongXuat = new javax.swing.JTextField();
        jComboBoxMaThuocXuat = new javax.swing.JComboBox();
        jComboBoxMaKhachHangXuat = new javax.swing.JComboBox();
        txtSTTXuat = new javax.swing.JTextField();
        txtMaHdXuat = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnInXuat = new javax.swing.JButton();
        btnThemXuat = new javax.swing.JButton();
        btnSuaXuat = new javax.swing.JButton();
        btnXoaXuat = new javax.swing.JButton();
        btnResetXuat = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jComboBoxSapXepXuat = new javax.swing.JComboBox();
        jPanel17 = new javax.swing.JPanel();
        jRadioButtonMaHdXuat = new javax.swing.JRadioButton();
        txtTimKiemHDXuat = new javax.swing.JTextField();
        jRadioButtonThanhTienXuat = new javax.swing.JRadioButton();
        jRadioButtonMaThuocHDXuat = new javax.swing.JRadioButton();
        jRadioButtonMaKHHDXuat = new javax.swing.JRadioButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setTitle("Hóa Đơn");

        jTabbedPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPaneMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Danh sách hóa đơn nhập");

        jTableHDNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableHDNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableHDNhapMouseClicked(evt);
            }
        });
        jTableHDNhap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableHDNhapKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableHDNhap);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hành động", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(153, 0, 153))); // NOI18N

        btnInNhap.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnInNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/print16x16.png"))); // NOI18N
        btnInNhap.setText("In");
        btnInNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInNhapActionPerformed(evt);
            }
        });

        btnThemNhap.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThemNhap.setForeground(new java.awt.Color(0, 204, 0));
        btnThemNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add16x16.png"))); // NOI18N
        btnThemNhap.setText("Thêm");
        btnThemNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNhapActionPerformed(evt);
            }
        });

        btnXoaNhap.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoaNhap.setForeground(new java.awt.Color(255, 0, 0));
        btnXoaNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/exit16x16.png"))); // NOI18N
        btnXoaNhap.setText("Xóa");
        btnXoaNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNhapActionPerformed(evt);
            }
        });

        btnSuaNhap.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSuaNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/fix16x16.png"))); // NOI18N
        btnSuaNhap.setText("Sửa");
        btnSuaNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaNhapActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/refesh16x16.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemNhap)
                .addGap(23, 23, 23)
                .addComponent(btnSuaNhap)
                .addGap(18, 29, Short.MAX_VALUE)
                .addComponent(btnXoaNhap)
                .addGap(22, 22, 22)
                .addComponent(btnInNhap)
                .addGap(24, 24, 24)
                .addComponent(btnReset)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnSuaNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXoaNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(btnThemNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setText("STT");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSTTNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSTTNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        jLabel2.setText("Mã hóa đơn");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtMaHDNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaHDNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        jLabel3.setText("Mã nhà cung cấp");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jComboBoxMaNhaCungCapNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxMaNhaCungCapNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel4.setText("Mã thuốc");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBoxMaThuocNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxMaThuocNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        jLabel5.setText("Số lượng");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSoLuongNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoLuongNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        jLabel6.setText("Giá nhập");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        jLabel7.setText("Thành tiền");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtThanhTienNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtThanhTienNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        jLabel8.setText("Đã thanh toán");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtThanhToanNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtThanhToanNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel18.setText("Ngày nhập");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dateChooserNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateChooserNhap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sắp xếp", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(51, 0, 204))); // NOI18N

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 153, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "STT", "Mã hóa đơn", "Nhà cung cấp", "Mã thuốc", "Giá nhập", "Ngày nhập" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, 0, 131, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(204, 0, 0))); // NOI18N

        buttonGroupHDNhap.add(jRadioButtonMaThuocNhap);
        jRadioButtonMaThuocNhap.setText("Mã thuốc");

        buttonGroupHDNhap.add(jRadioButtonMaHDNhap);
        jRadioButtonMaHDNhap.setText("Mã hóa đơn");

        buttonGroupHDNhap.add(jRadioButtonNhaCungCapNhap);
        jRadioButtonNhaCungCapNhap.setText("Nhà cung cấp");

        buttonGroupHDNhap.add(jRadioButtonThanhTienNhap);
        jRadioButtonThanhTienNhap.setText("Thành tiền");

        txtTimKiemHDNhap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemHDNhapKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonMaHDNhap)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonNhaCungCapNhap)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonMaThuocNhap)
                .addGap(26, 26, 26)
                .addComponent(jRadioButtonThanhTienNhap)
                .addGap(18, 18, 18)
                .addComponent(txtTimKiemHDNhap)
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonMaHDNhap)
                    .addComponent(jRadioButtonNhaCungCapNhap)
                    .addComponent(jRadioButtonMaThuocNhap)
                    .addComponent(jRadioButtonThanhTienNhap)
                    .addComponent(txtTimKiemHDNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(227, 227, 227))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Hóa đơn nhập", jPanel2);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Danh sách hóa đơn xuất");

        jTableHDXuat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableHDXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableHDXuatMouseClicked(evt);
            }
        });
        jTableHDXuat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableHDXuatKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTableHDXuat);

        jLabel16.setText("Giá xuất");

        jLabel19.setText("Đã thanh toán");

        jLabel15.setText("Số lượng");

        jLabel11.setText("STT");

        jLabel12.setText("Mã hóa đơn");

        jLabel20.setText("Ngày xuất");

        jLabel13.setText("Mã khách hàng");

        jLabel14.setText("Mã thuốc");

        jLabel17.setText("Thành tiền");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtThanhToanXuat)
                            .addComponent(dateChooserXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtThanhTienXuat)
                            .addComponent(txtGiaXuat)
                            .addComponent(txtSoLuongXuat)
                            .addComponent(jComboBoxMaThuocXuat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSTTXuat, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMaHdXuat)
                            .addComponent(jComboBoxMaKhachHangXuat, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSTTXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtMaHdXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jComboBoxMaKhachHangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jComboBoxMaThuocXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(txtSoLuongXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(txtGiaXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(txtThanhTienXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(txtThanhToanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateChooserXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hành động", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 153))); // NOI18N

        btnInXuat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnInXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/print16x16.png"))); // NOI18N
        btnInXuat.setText("In");
        btnInXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInXuatActionPerformed(evt);
            }
        });

        btnThemXuat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThemXuat.setForeground(new java.awt.Color(0, 153, 0));
        btnThemXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add16x16.png"))); // NOI18N
        btnThemXuat.setText("Thêm");
        btnThemXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemXuatActionPerformed(evt);
            }
        });

        btnSuaXuat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSuaXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/fix16x16.png"))); // NOI18N
        btnSuaXuat.setText("Sửa");
        btnSuaXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaXuatActionPerformed(evt);
            }
        });

        btnXoaXuat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoaXuat.setForeground(new java.awt.Color(204, 0, 0));
        btnXoaXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/exit16x16.png"))); // NOI18N
        btnXoaXuat.setText("Xóa");
        btnXoaXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaXuatActionPerformed(evt);
            }
        });

        btnResetXuat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnResetXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/refesh16x16.png"))); // NOI18N
        btnResetXuat.setText("Reset");
        btnResetXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemXuat)
                .addGap(24, 24, 24)
                .addComponent(btnSuaXuat)
                .addGap(23, 23, 23)
                .addComponent(btnXoaXuat)
                .addGap(20, 20, 20)
                .addComponent(btnInXuat)
                .addGap(18, 24, Short.MAX_VALUE)
                .addComponent(btnResetXuat)
                .addGap(13, 13, 13))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemXuat)
                    .addComponent(btnSuaXuat)
                    .addComponent(btnXoaXuat)
                    .addComponent(btnInXuat)
                    .addComponent(btnResetXuat))
                .addContainerGap())
        );

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sắp xếp", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 0, 0))); // NOI18N

        jComboBoxSapXepXuat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBoxSapXepXuat.setForeground(new java.awt.Color(0, 102, 0));
        jComboBoxSapXepXuat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mã hóa đơn", "Mã thuốc", "Giá xuất", "Ngày xuất" }));
        jComboBoxSapXepXuat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxSapXepXuatItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxSapXepXuat, 0, 154, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBoxSapXepXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(153, 0, 153))); // NOI18N

        buttonGroupHDXuat.add(jRadioButtonMaHdXuat);
        jRadioButtonMaHdXuat.setText("Mã hóa đơn");

        txtTimKiemHDXuat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemHDXuatKeyReleased(evt);
            }
        });

        buttonGroupHDXuat.add(jRadioButtonThanhTienXuat);
        jRadioButtonThanhTienXuat.setText("Thành tiền");

        buttonGroupHDXuat.add(jRadioButtonMaThuocHDXuat);
        jRadioButtonMaThuocHDXuat.setText("Mã thuốc");

        buttonGroupHDXuat.add(jRadioButtonMaKHHDXuat);
        jRadioButtonMaKHHDXuat.setText("Mã khách hàng");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonMaHdXuat)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonMaKHHDXuat)
                .addGap(36, 36, 36)
                .addComponent(jRadioButtonMaThuocHDXuat)
                .addGap(41, 41, 41)
                .addComponent(jRadioButtonThanhTienXuat)
                .addGap(18, 18, 18)
                .addComponent(txtTimKiemHDXuat)
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(txtTimKiemHDXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonMaHdXuat)
                            .addComponent(jRadioButtonMaKHHDXuat)
                            .addComponent(jRadioButtonMaThuocHDXuat)
                            .addComponent(jRadioButtonThanhTienXuat))))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
        );

        jTabbedPane.addTab("Hóa đơn xuất", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );

        setBounds(0, 0, 1005, 594);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNhapActionPerformed
        try {

            String sql = "Insert into TableHDNhap(STT,MaHoaDon,NhaCungCap,MaThuoc,SoLuong,GiaNhap,ThanhTien,DaThanhToan,NgayNhap) values (?,?,?,?,?,?,?,?,?)";

            pst = conn.prepareStatement(sql);
            pst.setString(1, txtSTTNhap.getText());

            pst.setString(2, txtMaHDNhap.getText());
            pst.setString(3, (String) jComboBoxMaNhaCungCapNhap.getSelectedItem());

            pst.setString(4, (String) jComboBoxMaThuocNhap.getSelectedItem());
            pst.setString(5, txtSoLuongNhap.getText());

            pst.setString(6, txtGiaNhap.getText());
            pst.setString(7, txtThanhTienNhap.getText());

            pst.setString(8, txtThanhToanNhap.getText());
            pst.setString(9, ((JTextField) dateChooserNhap.getDateEditor().getUiComponent()).getText());

            pst.execute();
            JOptionPane.showMessageDialog(null, "Lưu thành công");
            pst.close();
            rs.close();

        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        updateTableHoaDonNhap();
    }

    /*               
    }//GEN-LAST:event_btnThemNhapActionPerformed
*/

    private void btnSuaNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaNhapActionPerformed
        try {

            String value0 = txtSTTNhap.getText();
            String value1 = txtMaHDNhap.getText();
            String value2 = (String) jComboBoxMaNhaCungCapNhap.getSelectedItem();
            String value3 = (String) jComboBoxMaThuocNhap.getSelectedItem();
            String value4 = txtSoLuongNhap.getText();
            String value5 = txtGiaNhap.getText();
            String value6 = txtThanhTienNhap.getText();
            String value7 = txtThanhToanNhap.getText();
            String value8 = ((JTextField) dateChooserNhap.getDateEditor().getUiComponent()).getText();

            String sql = "update TableHDNhap set STT='" + value0 + "',MaHoaDon='" + value1 + "',NhaCungCap='" + value2 + "',MaThuoc='" + value3 + "',SoLuong='" + value4 + "',GiaNhap='" + value5 + "',ThanhTien='" + value6 + "',DaThanhToan='" + value7 + "',NgayNhap='" + value8 + "' where STT='" + value0 + "' ";

            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Sửa thành công");
            pst.close();
            rs.close();
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        updateTableHoaDonNhap();
    }//GEN-LAST:event_btnSuaNhapActionPerformed

    private void btnXoaNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNhapActionPerformed
        int p = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa", "Xóa", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            String sql = "delete from TableHDNhap where STT =?";
            try {
                pst = conn.prepareStatement(sql);
                pst.setString(1, txtSTTNhap.getText());
                pst.execute();
                JOptionPane.showMessageDialog(null, "Xóa thành công");
                pst.close();
                rs.close();
            } catch (SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, e);
            }
            updateTableHoaDonNhap();
        }
    }//GEN-LAST:event_btnXoaNhapActionPerformed

    private void btnInNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInNhapActionPerformed
        MessageFormat header = new MessageFormat("Danh sách hóa đơn nhập");
        MessageFormat footer = new MessageFormat("Pase{0,number,integer}");

        try {
            jTableHDNhap.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (Exception e) {
            System.err.format("Không thể in %s%n", e.getMessage());
        }
    }//GEN-LAST:event_btnInNhapActionPerformed

    private void btnThemXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemXuatActionPerformed
        try {

            String sql = "Insert into TableHDxuat(STT,MaHoaDon,MaKhachHang,MaThuoc,SoLuong,GiaXuat,ThanhTien,DaThanhToan,NgayXuat) values (?,?,?,?,?,?,?,?,?)";

            pst = conn.prepareStatement(sql);
            pst.setString(1, txtSTTXuat.getText());

            pst.setString(2, txtMaHdXuat.getText());
            pst.setString(3, (String) jComboBoxMaKhachHangXuat.getSelectedItem());

            pst.setString(4, (String) jComboBoxMaThuocXuat.getSelectedItem());
            pst.setString(5, txtSoLuongXuat.getText());

            pst.setString(6, txtGiaXuat.getText());
            pst.setString(7, txtThanhTienXuat.getText());

            pst.setString(8, txtThanhToanXuat.getText());
            pst.setString(9, ((JTextField) dateChooserXuat.getDateEditor().getUiComponent()).getText());

            pst.execute();
            JOptionPane.showMessageDialog(null, "Lưu thành công");
            pst.close();
            rs.close();
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        updateTableHoaDonXuat();
    }//GEN-LAST:event_btnThemXuatActionPerformed

    private void btnSuaXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaXuatActionPerformed
        try {

            String value0 = txtSTTXuat.getText();
            String value1 = txtMaHdXuat.getText();
            String value2 = (String) jComboBoxMaKhachHangXuat.getSelectedItem();
            String value3 = (String) jComboBoxMaThuocXuat.getSelectedItem();
            String value4 = txtSoLuongXuat.getText();
            String value5 = txtGiaXuat.getText();
            String value6 = txtThanhTienXuat.getText();
            String value7 = txtThanhToanXuat.getText();
            String value8 = ((JTextField) dateChooserXuat.getDateEditor().getUiComponent()).getText();

            String sql = "update TableHDxuat set STT='" + value0 + "',MaHoaDon='" + value1 + "',MaKhachHang='" + value2 + "',MaThuoc='" + value3 + "',SoLuong='" + value4 + "',GiaXuat='" + value5 + "',ThanhTien='" + value6 + "',DaThanhToan='" + value7 + "',NgayXuat='" + value8 + "' where STT='" + value0 + "' ";

            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Sửa thành công");
            pst.close();
            rs.close();
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        updateTableHoaDonXuat();
    }//GEN-LAST:event_btnSuaXuatActionPerformed

    private void btnXoaXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaXuatActionPerformed
        int p = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa", "Xóa", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            String sql = "delete from TableHDxuat where STT =?";
            try {
                pst = conn.prepareStatement(sql);
                pst.setString(1, txtSTTXuat.getText());
                pst.execute();
                JOptionPane.showMessageDialog(null, "Xóa thành công");
                pst.close();
                rs.close();
            } catch (SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, e);
            }
            updateTableHoaDonXuat();
        }
    }//GEN-LAST:event_btnXoaXuatActionPerformed

    private void btnInXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInXuatActionPerformed
        MessageFormat header = new MessageFormat("Danh sách hóa đơn xuất");
        MessageFormat footer = new MessageFormat("Pase{0,number,integer}");

        try {
            jTableHDXuat.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (Exception e) {
            System.err.format("Không thể in %s%n", e.getMessage());
        }
    }//GEN-LAST:event_btnInXuatActionPerformed

    private void jTableHDXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableHDXuatMouseClicked
        try {
            int row = jTableHDXuat.getSelectedRow();
            String tableClick = (jTableHDXuat.getModel().getValueAt(row, 0).toString());
            String sql = "Select * from TableHDxuat where STT='" + tableClick + "' ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {
                String add0 = rs.getString("STT");
                txtSTTXuat.setText(add0);
                String add1 = rs.getString("MaHoaDon");
                txtMaHdXuat.setText(add1);
                String add2 = rs.getString("MaKhachHang");
                jComboBoxMaKhachHangXuat.setSelectedItem(add2);

                String add3 = rs.getString("MaThuoc");
                jComboBoxMaThuocXuat.setSelectedItem(add3);
                String add4 = rs.getString("SoLuong");
                txtSoLuongXuat.setText(add4);

                String add5 = rs.getString("GiaXuat");
                txtGiaXuat.setText(add5);
                String add6 = rs.getString("ThanhTien");
                txtThanhTienXuat.setText(add6);

                String add7 = rs.getString("DaThanhToan");
                txtThanhToanXuat.setText(add7);
                String add8 = rs.getString("NgayXuat");
                Date date = new SimpleDateFormat("MMM d, yyyy").parse(add8);
                dateChooserXuat.setDate(date);
                pst.close();
                rs.close();
            }

        } catch (SQLException | ParseException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        updateTableHoaDonXuat();

    }//GEN-LAST:event_jTableHDXuatMouseClicked

    private void jTableHDNhapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableHDNhapKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP) {
            try {
                int row = jTableHDNhap.getSelectedRow();
                String tableClick = (jTableHDNhap.getModel().getValueAt(row, 0).toString());
                String sql = "Select * from TableHDNhap where STT='" + tableClick + "' ";
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                if (rs.next()) {
                    String add0 = rs.getString("STT");
                    txtSTTNhap.setText(add0);
                    String add1 = rs.getString("MaHoaDon");
                    txtMaHDNhap.setText(add1);
                    String add2 = rs.getString("NhaCungCap");
                    jComboBoxMaNhaCungCapNhap.setSelectedItem(add2);

                    String add3 = rs.getString("MaThuoc");
                    jComboBoxMaThuocNhap.setSelectedItem(add3);
                    String add4 = rs.getString("SoLuong");
                    txtSoLuongNhap.setText(add4);

                    String add5 = rs.getString("GiaNhap");
                    txtGiaNhap.setText(add5);
                    String add6 = rs.getString("ThanhTien");
                    txtThanhTienNhap.setText(add6);

                    String add7 = rs.getString("DaThanhToan");
                    txtThanhToanNhap.setText(add7);
                    String add8 = rs.getString("Ngaynhap");
                    Date date = new SimpleDateFormat("MMM d, yyyy").parse(add8);
                    dateChooserNhap.setDate(date);
                    pst.close();
                    rs.close();
                }

            } catch (SQLException | ParseException e) {
                JOptionPane.showMessageDialog(null, e);

            }
        }
    }//GEN-LAST:event_jTableHDNhapKeyPressed

    private void jTableHDXuatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableHDXuatKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP) {
            try {
                int row = jTableHDXuat.getSelectedRow();
                String tableClick = (jTableHDXuat.getModel().getValueAt(row, 0).toString());
                String sql = "Select * from TableHDxuat where STT='" + tableClick + "' ";
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                if (rs.next()) {
                    String add0 = rs.getString("STT");
                    txtSTTXuat.setText(add0);
                    String add1 = rs.getString("MaHoaDon");
                    txtMaHdXuat.setText(add1);
                    String add2 = rs.getString("MaKhachHang");
                    jComboBoxMaKhachHangXuat.setSelectedItem(add2);

                    String add3 = rs.getString("MaThuoc");
                    jComboBoxMaThuocXuat.setSelectedItem(add3);
                    String add4 = rs.getString("SoLuong");
                    txtSoLuongXuat.setText(add4);

                    String add5 = rs.getString("GiaXuat");
                    txtGiaXuat.setText(add5);
                    String add6 = rs.getString("ThanhTien");
                    txtThanhTienXuat.setText(add6);

                    String add7 = rs.getString("DaThanhToan");
                    txtThanhToanXuat.setText(add7);
                    String add8 = rs.getString("NgayXuat");
                    Date date = new SimpleDateFormat("MMM d, yyyy").parse(add8);
                    dateChooserXuat.setDate(date);
                    pst.close();
                    rs.close();
                }

            } catch (SQLException | ParseException e) {
                JOptionPane.showMessageDialog(null, e);

            }
        }
    }//GEN-LAST:event_jTableHDXuatKeyPressed

    private void jComboBoxSapXepXuatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxSapXepXuatItemStateChanged
        String sql = "select * from TableHDxuat order by STT";
        int index1 = jComboBoxSapXepXuat.getSelectedIndex();
        if (index1 == 0) {
           sql = "select * from TableHDxuat order by MaHoaDon asc";
        }
        if (index1 == 1) {
            sql = "select * from TableHDxuat order by MaThuoc asc";
        }
        if (index1 == 2) {
            sql = "select * from TableHDxuat order by GiaXuat asc";
        }
        if (index1 == 3) {
              sql = "select * from TableHDxuat order by NgayXuat asc";
        }
     
        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            jTableHDXuat.setModel(DbUtils.resultSetToTableModel(rs));
            pst.close();
            rs.close();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }//GEN-LAST:event_jComboBoxSapXepXuatItemStateChanged

    private void txtTimKiemHDXuatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemHDXuatKeyReleased
        TextAutoCompleter autoSeachHDXuat = new TextAutoCompleter(txtTimKiemHDXuat);
        String sql = null;

        if (jRadioButtonMaHdXuat.isSelected()) {
            sql = "select * from TableHDxuat where MaHoaDon=?";
        }
        if (jRadioButtonMaThuocHDXuat.isSelected()) {
            sql = "select * from TableHDxuat where MaThuoc=?";
        }
        if (jRadioButtonMaKHHDXuat.isSelected()) {
            sql = "select * from TableHDxuat where MaKhachHang=?";
        }
        if (jRadioButtonThanhTienXuat.isSelected()) {
            sql = "select * from TableHDxuat where ThanhTien=?";
        }

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, txtTimKiemHDXuat.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Hóa đơn cần tìm là :");
                String add0 = rs.getString("STT");
                txtSTTXuat.setText(add0);
                String add1 = rs.getString("MaHoaDon");
                txtMaHdXuat.setText(add1);
                String add2 = rs.getString("MaKhachHang");
                jComboBoxMaKhachHangXuat.setSelectedItem(add2);

                String add3 = rs.getString("MaThuoc");
                jComboBoxMaThuocXuat.setSelectedItem(add3);
                String add4 = rs.getString("SoLuong");
                txtSoLuongXuat.setText(add4);

                String add5 = rs.getString("GiaXuat");
                txtGiaXuat.setText(add5);
                String add6 = rs.getString("ThanhTien");
                txtThanhTienXuat.setText(add6);

                String add7 = rs.getString("DaThanhToan");
                txtThanhToanXuat.setText(add7);
                String add8 = rs.getString("NgayXuat");
                Date date = new SimpleDateFormat("MMM d, yyyy").parse(add8);
                dateChooserXuat.setDate(date);
                pst.close();
                rs.close();
            }

        } catch (SQLException | HeadlessException | ParseException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_txtTimKiemHDXuatKeyReleased

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        String sql = "select * from TableHDNhap order by STT";
        int index = jComboBox1.getSelectedIndex();
        if (index == 0) {
            sql = "select * from TableHDNhap order by STT";
        }
        if (index == 1) {
            sql = "select * from TableHDNhap order by MaHoaDon";
        }
        if (index == 2) {
            sql = "select * from TableHDNhap order by NhaCungCap";
        }
        if (index == 3) {
            sql = "select * from TableHDNhap order by MaThuoc";
        }
        if (index == 4) {
            sql = "select * from TableHDNhap order by GiaNhap";
        }
        if (index == 5) {
            sql = "select * from TableHDNhap order by NgayNhap";
        }
        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            jTableHDNhap.setModel(DbUtils.resultSetToTableModel(rs));
            pst.close();
            rs.close();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void txtTimKiemHDNhapKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemHDNhapKeyReleased
        TextAutoCompleter autoSeachHDNhap = new TextAutoCompleter(txtTimKiemHDNhap);
        String sql = null;

        if (jRadioButtonMaHDNhap.isSelected()) {
            sql = "select * from TableHDNhap where MaHoaDon=?";
        }
        if (jRadioButtonMaThuocNhap.isSelected()) {
            sql = "select * from TableHDNhap where MaThuoc=?";
        }
        if (jRadioButtonNhaCungCapNhap.isSelected()) {
            sql = "select * from TableHDNhap where NhaCungCap=?";
        }
        if (jRadioButtonThanhTienNhap.isSelected()) {
            sql = "select * from TableHDNhap where ThanhTien=?";
        }

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, txtTimKiemHDNhap.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Hóa đơn cần tìm là : ");
                String add0 = rs.getString("STT");
                txtSTTNhap.setText(add0);
                String add1 = rs.getString("MaHoaDon");
                txtMaHDNhap.setText(add1);
                String add2 = rs.getString("NhaCungCap");
                jComboBoxMaNhaCungCapNhap.setSelectedItem(add2);

                String add3 = rs.getString("MaThuoc");
                jComboBoxMaThuocNhap.setSelectedItem(add3);
                String add4 = rs.getString("SoLuong");
                txtSoLuongNhap.setText(add4);

                String add5 = rs.getString("GiaNhap");
                txtGiaNhap.setText(add5);
                String add6 = rs.getString("ThanhTien");
                txtThanhTienNhap.setText(add6);

                String add7 = rs.getString("DaThanhToan");
                txtThanhToanNhap.setText(add7);
                String add8 = rs.getString("Ngaynhap");
                Date date = new SimpleDateFormat("MMM d, yyyy").parse(add8);
                dateChooserNhap.setDate(date);
                pst.close();
                rs.close();
            }
        } catch (SQLException | ParseException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_txtTimKiemHDNhapKeyReleased

    private void jTableHDNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableHDNhapMouseClicked
        try {
            int row = jTableHDNhap.getSelectedRow();
            String tableClick = (jTableHDNhap.getModel().getValueAt(row, 0).toString());
            String sql = "Select * from TableHDNhap where STT='" + tableClick + "' ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {
                String add0 = rs.getString("STT");
                txtSTTNhap.setText(add0);
                String add1 = rs.getString("MaHoaDon");
                txtMaHDNhap.setText(add1);
                String add2 = rs.getString("NhaCungCap");
                jComboBoxMaNhaCungCapNhap.setSelectedItem(add2);

                String add3 = rs.getString("MaThuoc");
                jComboBoxMaThuocNhap.setSelectedItem(add3);
                String add4 = rs.getString("SoLuong");
                txtSoLuongNhap.setText(add4);

                String add5 = rs.getString("GiaNhap");
                txtGiaNhap.setText(add5);
                String add6 = rs.getString("ThanhTien");
                txtThanhTienNhap.setText(add6);

                String add7 = rs.getString("DaThanhToan");
                txtThanhToanNhap.setText(add7);
                String add8 = rs.getString("Ngaynhap");
                Date date = new SimpleDateFormat("MMM d, yyyy").parse(add8);
                dateChooserNhap.setDate(date);
                pst.close();
                rs.close();
            }

        } catch (SQLException | ParseException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        updateTableHoaDonNhap();
    }//GEN-LAST:event_jTableHDNhapMouseClicked

    private void jTabbedPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPaneMouseClicked
        updateTableHoaDonNhap();
        updateTableHoaDonXuat();
    }//GEN-LAST:event_jTabbedPaneMouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtSTTNhap.setText("");
        txtMaHDNhap.setText("");
        jComboBoxMaNhaCungCapNhap.setSelectedItem(evt);
        jComboBoxMaThuocNhap.setSelectedItem(evt);
        txtSoLuongNhap.setText("");
        txtGiaNhap.setText("");
        txtThanhTienNhap.setText("");
        txtThanhToanNhap.setText("");
        dateChooserNhap.setDate(null);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnResetXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetXuatActionPerformed

        txtSTTXuat.setText("");
        txtMaHdXuat.setText("");
        jComboBoxMaKhachHangXuat.setSelectedItem(evt);
        jComboBoxMaThuocXuat.setSelectedItem(evt);
        txtSoLuongXuat.setText("");
        txtGiaXuat.setText("");
        txtThanhTienXuat.setText("");
        txtThanhToanXuat.setText("");
        dateChooserXuat.setDate(null);
    }//GEN-LAST:event_btnResetXuatActionPerformed

    private void fillComboMaThuoc() {

        try {
            String sql = "Select * from TableThuoc";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String maThuoc = rs.getString("MaThuoc");
                jComboBoxMaThuocNhap.addItem(maThuoc);
                jComboBoxMaThuocXuat.addItem(maThuoc);

            }
            pst.close();
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void fillComboMaNhaCungCapNhap() {

        try {
            String sql = "Select * from TableThuoc";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String maNhaCungCap = rs.getString("NhaCungCap");
                jComboBoxMaNhaCungCapNhap.addItem(maNhaCungCap);
            }
            pst.close();
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void fillComboMaKhachHangXuat() {

        try {
            String sql = "Select * from TableKhachHang";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String maKhachHang = rs.getString("MaKhachHang");
                jComboBoxMaKhachHangXuat.addItem(maKhachHang);
            }
            pst.close();
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInNhap;
    private javax.swing.JButton btnInXuat;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnResetXuat;
    private javax.swing.JButton btnSuaNhap;
    private javax.swing.JButton btnSuaXuat;
    private javax.swing.JButton btnThemNhap;
    private javax.swing.JButton btnThemXuat;
    private javax.swing.JButton btnXoaNhap;
    private javax.swing.JButton btnXoaXuat;
    private javax.swing.ButtonGroup buttonGroupHDNhap;
    private javax.swing.ButtonGroup buttonGroupHDXuat;
    private com.toedter.calendar.JDateChooser dateChooserNhap;
    private com.toedter.calendar.JDateChooser dateChooserXuat;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBoxMaKhachHangXuat;
    private javax.swing.JComboBox jComboBoxMaNhaCungCapNhap;
    private javax.swing.JComboBox jComboBoxMaThuocNhap;
    private javax.swing.JComboBox jComboBoxMaThuocXuat;
    private javax.swing.JComboBox jComboBoxSapXepXuat;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButtonMaHDNhap;
    private javax.swing.JRadioButton jRadioButtonMaHdXuat;
    private javax.swing.JRadioButton jRadioButtonMaKHHDXuat;
    private javax.swing.JRadioButton jRadioButtonMaThuocHDXuat;
    private javax.swing.JRadioButton jRadioButtonMaThuocNhap;
    private javax.swing.JRadioButton jRadioButtonNhaCungCapNhap;
    private javax.swing.JRadioButton jRadioButtonThanhTienNhap;
    private javax.swing.JRadioButton jRadioButtonThanhTienXuat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTableHDNhap;
    private javax.swing.JTable jTableHDXuat;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JTextField txtGiaXuat;
    private javax.swing.JTextField txtMaHDNhap;
    private javax.swing.JTextField txtMaHdXuat;
    private javax.swing.JTextField txtSTTNhap;
    private javax.swing.JTextField txtSTTXuat;
    private javax.swing.JTextField txtSoLuongNhap;
    private javax.swing.JTextField txtSoLuongXuat;
    private javax.swing.JTextField txtThanhTienNhap;
    private javax.swing.JTextField txtThanhTienXuat;
    private javax.swing.JTextField txtThanhToanNhap;
    private javax.swing.JTextField txtThanhToanXuat;
    private javax.swing.JTextField txtTimKiemHDNhap;
    private javax.swing.JTextField txtTimKiemHDXuat;
    // End of variables declaration//GEN-END:variables
}
