/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_management;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Tài
 */
public class MainActivity extends JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    String useName;
    String password;
    int admin;

    HoaDon hoaDon = null;
    KhachHang khachHang = null;
    Thuoc thuoc = null;
    TaiKhoanAdmin taiKhoanAdmin = null;
    TaiKhoan taiKhoan = null;
    ThongTin thongTin = null;

    /**
     * Creates new form Employee_info
     */
    public MainActivity() {
        initComponents();
        admin = Login.admin;
        conn = JavaConnect.ConnectDB();
        displayAllTable();
        new Thread() {
            @Override
            public void run() {
                useName = Login.useNameLogin;
                labelUseName.setText(useName);
                while (true) {
                    Calendar cal = new GregorianCalendar();
                    //hien thi ngay thang nam
                    int day = cal.get(Calendar.DAY_OF_MONTH);
                    int month = cal.get(Calendar.MONTH);
                    int year = cal.get(Calendar.YEAR);
                    
                    labelDate.setText(day + "/" + (month + 1) + "/" + year);
                    // hien thi thoi gian 
                    int sec = cal.get(Calendar.SECOND);
                    int min = cal.get(Calendar.MINUTE);
                    int hour = cal.get(Calendar.HOUR_OF_DAY);
                    String formatSec = String.format("%02d", sec);
                    String formatMin = String.format("%02d", min);
                    String formatHour = String.format("%02d", hour);

                    labelTime.setText(formatHour + ":" + formatMin + ":" + formatSec);
                }
            }

        }.start();
    }

    //Display all table in jdesktop table

    private void displayAllTable() {
        thuoc = new Thuoc();
        thuoc.setVisible(true);
        jDestopTable.add(thuoc);

        khachHang = new KhachHang();
        khachHang.setVisible(true);
        jDestopTable.add(khachHang);

        hoaDon = new HoaDon();
        hoaDon.setVisible(true);
        jDestopTable.add(hoaDon);

        thongTin = new ThongTin();
        thongTin.setVisible(true);
        jDestopTable.add(thongTin);
        if (admin == 1) {
            taiKhoanAdmin = new TaiKhoanAdmin();
            taiKhoanAdmin.setVisible(true);
            jDestopTable.add(taiKhoanAdmin);
        } else {
            taiKhoan = new TaiKhoan();
            taiKhoan.setVisible(true);
            jDestopTable.add(taiKhoan);
        }
    }

    //close windown login

    public void closeWindownMainActivity() {
        WindowEvent winClosingEven = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEven);
    }

    //update current time and date

    private void currentDateTime() {
        //hien thi tai khoan len labelUseName
        useName = Login.useNameLogin;
        labelUseName.setText(useName);
        Calendar cal = new GregorianCalendar();
        //hien thi ngay thang nam
        int day = cal.get(Calendar.DAY_OF_MONTH);
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        labelDate.setText(day + "/" + (month + 1) + "/" + year);
        // hien thi thoi gian 
        int sec = cal.get(Calendar.SECOND);
        int min = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR);
        if (min < 10) {
            labelTime.setText(hour + ":" + "0" + min + ":" + sec);
        } else {
            if (sec < 10) {
                labelTime.setText(hour + ":" + min + ":" + "0" + sec);
            } else {
                labelTime.setText(hour + ":" + min + ":" + sec);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelUseName = new javax.swing.JLabel();
        labelDate = new javax.swing.JLabel();
        labelTime = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbDangXuat = new javax.swing.JLabel();
        jDestopTable = new javax.swing.JDesktopPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuThuoc = new javax.swing.JMenu();
        jMenuHoaDonNhap = new javax.swing.JMenu();
        jMenuKhachHang = new javax.swing.JMenu();
        jMenuTaiKhoan = new javax.swing.JMenu();
        jMenuThongTin = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("HỆ THỐNG QUẢN LÝ HIỆU THUỐC");

        jPanel1.setBackground(new java.awt.Color(51, 255, 51));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setText("Giờ    :");

        jLabel3.setText("Ngày :");

        jLabel2.setText("Tài khoản :");

        labelUseName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user-group.png"))); // NOI18N

        lbDangXuat.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lbDangXuat.setText("Đăng xuất");
        lbDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDangXuatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelUseName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(labelUseName, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(labelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTime, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbDangXuat))
        );

        javax.swing.GroupLayout jDestopTableLayout = new javax.swing.GroupLayout(jDestopTable);
        jDestopTable.setLayout(jDestopTableLayout);
        jDestopTableLayout.setHorizontalGroup(
            jDestopTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDestopTableLayout.setVerticalGroup(
            jDestopTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/supplier-95.png"))); // NOI18N

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("QUẢN  LÝ  HIỆU  THUỐC");

        jMenuThuoc.setText("Thuốc");
        jMenuThuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuThuocMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuThuoc);

        jMenuHoaDonNhap.setText("Hóa Đơn");
        jMenuHoaDonNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuHoaDonNhapMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuHoaDonNhap);

        jMenuKhachHang.setText("Khách Hàng");
        jMenuKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuKhachHangMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuKhachHang);

        jMenuTaiKhoan.setText("Tài Khoản");
        jMenuTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuTaiKhoanMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuTaiKhoan);

        jMenuThongTin.setText("Thông Tin");
        jMenuThongTin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuThongTinMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuThongTin);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleName("rêf");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDestopTable))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDestopTable)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuKhachHangMouseClicked
        // TODO add your handling code here:
        // closeWindown();
        if (khachHang == null) {
            khachHang = new KhachHang();
            khachHang.setVisible(true);
            jDestopTable.add(khachHang);

        } else {
            khachHang.setVisible(true);
            hoaDon.setVisible(false);
            thuoc.setVisible(false);
            if (admin == 1) {
                taiKhoanAdmin.setVisible(false);
            } else {
                taiKhoan.setVisible(false);
            }
            thongTin.setVisible(false);
        }
    }//GEN-LAST:event_jMenuKhachHangMouseClicked

    private void jMenuHoaDonNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuHoaDonNhapMouseClicked
        if (hoaDon == null) {
            hoaDon = new HoaDon();

            hoaDon.setVisible(true);
            jDestopTable.add(hoaDon);

        } else {
            hoaDon.setVisible(true);
            khachHang.setVisible(false);
            thuoc.setVisible(false);
            if (admin == 1) {
                taiKhoanAdmin.setVisible(false);
            } else {
                taiKhoan.setVisible(false);
            }
            thongTin.setVisible(false);
        }

    }//GEN-LAST:event_jMenuHoaDonNhapMouseClicked

    private void jMenuThuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuThuocMouseClicked
        // TODO add your handling code here:
        if (thuoc == null) {
            thuoc = new Thuoc();
            thuoc.setVisible(true);
            jDestopTable.add(thuoc);
        } else {
            thuoc.setVisible(true);
            khachHang.setVisible(false);
            hoaDon.setVisible(false);
            if (admin == 1) {
                taiKhoanAdmin.setVisible(false);
            } else {
                taiKhoan.setVisible(false);
            }
            thongTin.setVisible(false);

        }
    }//GEN-LAST:event_jMenuThuocMouseClicked

    private void jMenuTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuTaiKhoanMouseClicked
        // TODO add your handling code here:
        if (admin == 1) {
            if (taiKhoanAdmin == null) {
                taiKhoanAdmin = new TaiKhoanAdmin();
                taiKhoanAdmin.setVisible(true);
                jDestopTable.add(taiKhoanAdmin);
            } else {
                taiKhoanAdmin.setVisible(true);
                thuoc.setVisible(false);
                hoaDon.setVisible(false);
                khachHang.setVisible(false);
                thongTin.setVisible(false);
            }
        } else {
            if (taiKhoan == null) {
                taiKhoan = new TaiKhoan();
                taiKhoan.setVisible(true);
                jDestopTable.add(taiKhoan);
            } else {
                taiKhoan.setVisible(true);
                thuoc.setVisible(false);
                hoaDon.setVisible(false);
                khachHang.setVisible(false);
                thongTin.setVisible(false);
            }
        }
    }//GEN-LAST:event_jMenuTaiKhoanMouseClicked

    private void lbDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDangXuatMouseClicked

        closeWindownMainActivity();
        Login login = new Login();
        login.setVisible(true);

    }//GEN-LAST:event_lbDangXuatMouseClicked

    private void jMenuThongTinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuThongTinMouseClicked
        if (thongTin == null) {
            thongTin = new ThongTin();
            thongTin.setVisible(true);
            jDestopTable.add(thongTin);
        } else {
            thongTin.setVisible(true);
            if (admin == 1) {
                taiKhoanAdmin.setVisible(false);
            } else {
                taiKhoan.setVisible(false);
            }
            thuoc.setVisible(false);
            hoaDon.setVisible(false);
            khachHang.setVisible(false);

        }
    }//GEN-LAST:event_jMenuThongTinMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainActivity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDestopTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuHoaDonNhap;
    private javax.swing.JMenu jMenuKhachHang;
    private javax.swing.JMenu jMenuTaiKhoan;
    private javax.swing.JMenu jMenuThongTin;
    private javax.swing.JMenu jMenuThuoc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelTime;
    private javax.swing.JLabel labelUseName;
    private javax.swing.JLabel lbDangXuat;
    // End of variables declaration//GEN-END:variables
}
