/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_management;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
/**
 *
 * @author Tài
 */
public class MainActivity extends JFrame {
        
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    String useName;
    String password;
    HoaDonNhap hoaDonNhap = null;
    HoaDonXuat hoaDonXuat = null;
    KhachHang khachHang = null;
    Medicine_New thuoc = null;
    TaiKhoan taiKhoan = null;
    /**
     * Creates new form Employee_info
     */
    public MainActivity() {
        initComponents();
        conn = ConnectDatabase.ConnectDB();
       // updateTable();
        new Thread(){
            @Override
            public void run(){
                useName = Login.useNameLogin;
                labelUseName.setText(useName);
                
                while (true) {          
                    Calendar cal = new GregorianCalendar();
                    //hien thi ngay thang nam
                    int day = cal.get(Calendar.DAY_OF_MONTH);
                    int month = cal.get(Calendar.MONTH);
                    int year = cal.get(Calendar.YEAR);
                    labelDate.setText(day+"/"+(month+1)+"/"+year);
                    // hien thi thoi gian 
                    int sec = cal.get(Calendar.SECOND);
                    int min = cal.get(Calendar.MINUTE);
                    int hour = cal.get(Calendar.HOUR_OF_DAY);
                    String formatSec = String.format("%02d", sec);
                    String formatMin = String.format("%02d", min);
                    String formatHour = String.format("%02d", hour);
                   
                    labelTime.setText(formatHour + ":" + formatMin + ":" + formatSec);
                    }
            }

        }.start();
        
    displayAllTable();
        
    }
    //Display all table in jdesktop table
    private void displayAllTable(){
        thuoc = new Medicine_New();
        thuoc.setVisible(true);
        jDestopTable.add(thuoc);
     
        hoaDonNhap = new HoaDonNhap();
        hoaDonNhap.setVisible(true);
        jDestopTable.add(hoaDonNhap);
       
        khachHang = new KhachHang();
        khachHang.setVisible(true);
        jDestopTable.add(khachHang);
        
        hoaDonXuat = new HoaDonXuat();
        hoaDonXuat.setVisible(true);
        jDestopTable.add(hoaDonXuat);
        
        taiKhoan = new TaiKhoan();
        taiKhoan.setVisible(true);
        jDestopTable.add(taiKhoan);
    
    }
    //close windown login
    public void closeWindownMainActivity() {
         WindowEvent winClosingEven = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEven);
    }
    //update current time and date
    private void currentDateTime(){
        //hien thi tai khoan len labelUseName
            useName = Login.useNameLogin;
            labelUseName.setText(useName);
            Calendar cal = new GregorianCalendar();
            //hien thi ngay thang nam
            int day = cal.get(Calendar.DAY_OF_MONTH);
            int month = cal.get(Calendar.MONTH);
            int year = cal.get(Calendar.YEAR);
            labelDate.setText(day+"/"+(month+1)+"/"+year);
            // hien thi thoi gian 
            int sec = cal.get(Calendar.SECOND);
            int min = cal.get(Calendar.MINUTE);
            int hour = cal.get(Calendar.HOUR);
            if(min<10){
                labelTime.setText(hour+":"+"0"+min+":"+sec);
            }
            else {
                if(sec<10){
                    labelTime.setText(hour+":"+min+":"+"0"+sec);
                }
                else 
                    labelTime.setText(hour+":"+min+":"+sec);
            }
            

    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelUseName = new javax.swing.JLabel();
        labelDate = new javax.swing.JLabel();
        labelTime = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDestopTable = new javax.swing.JDesktopPane();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuThuoc = new javax.swing.JMenu();
        jMenuHoaDonNhap = new javax.swing.JMenu();
        jMenuHoaDonXuat = new javax.swing.JMenu();
        jMenuKhachHang = new javax.swing.JMenu();
        jMenuTaiKhoan = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("HỆ THỐNG QUẢN LÝ HIỆU THUỐC");

        jPanel1.setBackground(new java.awt.Color(51, 255, 51));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setText("Giờ    :");

        jLabel3.setText("Ngày :");

        jLabel2.setText("Tài khoản :");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/User-32x32.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel6.setText("Đăng xuất");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelUseName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(labelUseName, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(labelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTime, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6))
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/banner.png"))); // NOI18N

        javax.swing.GroupLayout jDestopTableLayout = new javax.swing.GroupLayout(jDestopTable);
        jDestopTable.setLayout(jDestopTableLayout);
        jDestopTableLayout.setHorizontalGroup(
            jDestopTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDestopTableLayout.setVerticalGroup(
            jDestopTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/red-cross-64x64.png"))); // NOI18N

        jMenuThuoc.setText("Thuốc");
        jMenuThuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuThuocMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuThuoc);

        jMenuHoaDonNhap.setText("Hóa đơn nhập");
        jMenuHoaDonNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuHoaDonNhapMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuHoaDonNhap);

        jMenuHoaDonXuat.setText("Hóa đơn xuất");
        jMenuHoaDonXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuHoaDonXuatMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuHoaDonXuat);

        jMenuKhachHang.setText("Khách hàng");
        jMenuKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuKhachHangMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuKhachHang);

        jMenuTaiKhoan.setText("Tài khoản");
        jMenuTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuTaiKhoanMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuTaiKhoan);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleName("rêf");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jDestopTable))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDestopTable)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuKhachHangMouseClicked
        // TODO add your handling code here:
       // closeWindown();
        if(khachHang == null){
            khachHang = new KhachHang();
            khachHang.setVisible(true);
            jDestopTable.add(khachHang);
           // hoaDon.setVisible(false);
        }else {
                khachHang.setVisible(true);
                hoaDonNhap.setVisible(false);
                hoaDonXuat.setVisible(false);
                thuoc.setVisible(false);
                taiKhoan.setVisible(false);
        }
    }//GEN-LAST:event_jMenuKhachHangMouseClicked
    
    private void jMenuHoaDonNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuHoaDonNhapMouseClicked
   
        if(hoaDonNhap == null){
            hoaDonNhap = new HoaDonNhap();
            hoaDonNhap.setVisible(true);
            jDestopTable.add(hoaDonNhap);
          
        }else {
            hoaDonNhap.setVisible(true);
            hoaDonXuat.setVisible(false);
            khachHang.setVisible(false);
            thuoc.setVisible(false);
            taiKhoan.setVisible(false);
        }
       
    }//GEN-LAST:event_jMenuHoaDonNhapMouseClicked

    private void jMenuThuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuThuocMouseClicked
        // TODO add your handling code here:
        if(thuoc == null){
            thuoc = new Medicine_New();
            thuoc.setVisible(true);
            jDestopTable.add(thuoc);
        }else {
            thuoc.setVisible(true);
            khachHang.setVisible(false);
            hoaDonNhap.setVisible(false);
            hoaDonXuat.setVisible(false);
            taiKhoan.setVisible(false);
        }
    }//GEN-LAST:event_jMenuThuocMouseClicked

    private void jMenuTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuTaiKhoanMouseClicked
        // TODO add your handling code here:
        if(taiKhoan == null){
            taiKhoan = new TaiKhoan();
            taiKhoan.setVisible(true);
            jDestopTable.add(taiKhoan);
        }else {
            taiKhoan.setVisible(true);
            thuoc.setVisible(false);
            hoaDonNhap.setVisible(false);
            hoaDonXuat.setVisible(false);
            khachHang.setVisible(false);
        }
    }//GEN-LAST:event_jMenuTaiKhoanMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
            
        closeWindownMainActivity();
        Login login = new Login();
        login.setVisible(true);
        
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jMenuHoaDonXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuHoaDonXuatMouseClicked
         if(hoaDonXuat == null){
            hoaDonXuat = new HoaDonXuat();
            
            hoaDonXuat.setVisible(true);
            jDestopTable.add(hoaDonXuat);
           // khachHang.setVisible(false);
        }else {
            hoaDonNhap.setVisible(false);
            hoaDonXuat.setVisible(true);
            khachHang.setVisible(false);
            thuoc.setVisible(false);
            taiKhoan.setVisible(false);
        }
    }//GEN-LAST:event_jMenuHoaDonXuatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainActivity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDestopTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuHoaDonNhap;
    private javax.swing.JMenu jMenuHoaDonXuat;
    private javax.swing.JMenu jMenuKhachHang;
    private javax.swing.JMenu jMenuTaiKhoan;
    private javax.swing.JMenu jMenuThuoc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelTime;
    private javax.swing.JLabel labelUseName;
    // End of variables declaration//GEN-END:variables
}
