/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_management;

import com.mxrck.autocompleter.TextAutoCompleter;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Tran Dat
 */
public class Medicine_New extends javax.swing.JInternalFrame {
     Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form Medicine_New
     */
    public Medicine_New() {
        initComponents();
         //conn = ConnectDatabase.ConnectDB();   
        conn = JavaConnect.connecrDB();
        UpdateTableMedicine();
        AutoCompleteThuoc();
    }
    // Auto completer some text field in medicine
     public final void AutoCompleteThuoc(){
        TextAutoCompleter autoMaThuoc = new TextAutoCompleter(txt_mathuoc);
        TextAutoCompleter autoTenThuoc = new TextAutoCompleter(txt_tenthuoc);
        TextAutoCompleter autoNhaCungCap = new TextAutoCompleter(txt_tennhacungcap);
        TextAutoCompleter autoNuocSanXuat = new TextAutoCompleter(txt_nuocsanxuat);
        
        try{
            
            String sql ="Select * from Medicine";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {                
                String maThuoc = rs.getString("ma_thuoc");
                autoMaThuoc.addItem(maThuoc);
                String tenThuoc = rs.getString("ten_thuoc");
                autoTenThuoc.addItem(tenThuoc);
                String nhaCungCap = rs.getString("nha_san_xuat");
                autoNhaCungCap.addItem(nhaCungCap);
                String nuocSanXuat = rs.getString("nuoc_san_xuat");
                autoNuocSanXuat.addItem(nuocSanXuat);
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
private void UpdateTableMedicine() {

        try {
            String sql = "select * from Medicine";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            jtblist.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_mathuoc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_tenthuoc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_tenloaithuoc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_tennhacungcap = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_soluong = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_dongia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_nuocsanxuat = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_hamluong = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_congdung = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblist = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItemSeachMaThuoc = new javax.swing.JMenuItem();
        jMenuItemSeachTenThuoc = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jPanel2.setToolTipText("Thông tin thuốc");

        jLabel2.setText("Mã thuốc");

        jLabel3.setText("Tên thuốc");

        jLabel4.setText("Tên loại thuốc");

        jLabel5.setText("Tên nhà cung cấp ");

        jLabel6.setText("Số lượng ");

        jLabel7.setText("Đơn giá");

        jLabel8.setText("Nước sản xuất");

        jLabel9.setText("Hạn sử dụng");

        jLabel10.setText("Ngày sản xuất");

        jLabel11.setText("Hàm lượng");

        jLabel12.setText("Công dụng");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(44, 44, 44))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(21, 21, 21))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(43, 43, 43))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(51, 51, 51))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(37, 37, 37))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(36, 36, 36)))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_tenthuoc)
                    .addComponent(txt_tenloaithuoc)
                    .addComponent(txt_tennhacungcap)
                    .addComponent(txt_soluong)
                    .addComponent(txt_dongia)
                    .addComponent(txt_nuocsanxuat)
                    .addComponent(txt_mathuoc, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(txt_hamluong)
                    .addComponent(txt_congdung))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(txt_mathuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(txt_tenthuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(txt_tenloaithuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(txt_tennhacungcap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(txt_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(txt_dongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addComponent(txt_nuocsanxuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel9)
                .addGap(25, 25, 25)
                .addComponent(jLabel10)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel11)
                    .addComponent(txt_hamluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel12)
                    .addComponent(txt_congdung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jtblist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblist);

        jMenu1.setText("Option");

        jMenu3.setText("Thông tin thuốc");

        jMenuItem1.setText("Thêm loại thuốc");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Thay đổi thông tin thuốc");
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Cập nhật thông tin thuốc");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("In thông tin thuốc");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenu1.add(jMenu3);

        jMenu4.setText("Xóa");

        jMenuItem5.setText("Xóa một loại thuốc");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuItem6.setText("Xóa loại thuốc đã chọn");
        jMenu4.add(jMenuItem6);

        jMenuItem7.setText("Xóa tất cả");
        jMenu4.add(jMenuItem7);

        jMenu1.add(jMenu4);

        jMenu5.setText("Sắp xếp ");

        jMenuItem8.setText("Sắp xếp theo tên");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem8);

        jMenuItem9.setText("Sắp xếp theo thời gian nhập");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem9);

        jMenuItem10.setText("Sắp xếp theo hạn sử dụng");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);

        jMenuItem11.setText("Sắp xếp theo ngày sản xuất");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem11);

        jMenuItem12.setText("Sắp xếp theo mã thuốc");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem12);

        jMenu1.add(jMenu5);

        jMenu6.setText("Tìm thuốc");

        jMenuItemSeachMaThuoc.setText("Tìm theo mã thuốc");
        jMenuItemSeachMaThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSeachMaThuocActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemSeachMaThuoc);

        jMenuItemSeachTenThuoc.setText("Tìm theo tên thuốc");
        jMenuItemSeachTenThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSeachTenThuocActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemSeachTenThuoc);

        jMenu1.add(jMenu6);

        jMenu7.setText("Thuốc hết hạn");

        jMenuItem14.setText("Tạo danh sách");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem14);

        jMenuItem15.setText("Danh sách");
        jMenu7.add(jMenuItem15);

        jMenu1.add(jMenu7);

        jMenu8.setText("Gửi thông tin đến máy khác");
        jMenu1.add(jMenu8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         Calendar cal = new GregorianCalendar();
            int year = cal.get(Calendar.YEAR);
            int month = cal.get(Calendar.MONTH);
            int day = cal.get(Calendar.DAY_OF_MONTH);         
            String datetime = day+"/"+(month+1)+"/"+year;
        try {
            String sql = "Insert into Medicine (ma_thuoc,ten_thuoc,loai_thuoc,nha_san_xuat,so_luong,don_gia,nuoc_san_xuat,han_dung,ngay_sx,ham_luong,cong_dung,Time_enter) values (?,?,?,?,?,?,?,?,?,?,?,?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_mathuoc.getText());
            pst.setString(2, txt_tenthuoc.getText());
            pst.setString(3, txt_tenloaithuoc.getText());
            pst.setString(4, txt_tennhacungcap.getText());
            pst.setString(5, txt_soluong.getText());
            pst.setString(6, txt_dongia.getText());
            pst.setString(7, txt_nuocsanxuat.getText());
            pst.setString(8, ((JTextField) jdate_hansudung.getDateEditor().getUiComponent()).getText());                   
            pst.setString(9, ((JTextField) jdate_ngaysanxuat.getDateEditor().getUiComponent()).getText());
            pst.setString(10, txt_hamluong.getText());
            pst.setString(11, txt_congdung.getText());
            pst.setString(12, datetime);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Added!!");
            UpdateTableMedicine();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        
        Calendar cal = new GregorianCalendar();
            int year = cal.get(Calendar.YEAR);
            int month = cal.get(Calendar.MONTH);
            int day = cal.get(Calendar.DAY_OF_MONTH);         
            String datetime = day+"/"+(month+1)+"/"+year;
         try{
           // 
           // 
            String value0 = txt_mathuoc.getText();
            String value1 = txt_tenthuoc.getText();
            String value2 = txt_tenloaithuoc.getText();
            String value3 = txt_tennhacungcap.getText();
            String value4 = txt_soluong.getText();
            String value5 = txt_dongia.getText();
            String value6 = txt_nuocsanxuat.getText();
            String value7 = ((JTextField)jdate_hansudung.getDateEditor().getUiComponent()).getText();
            String value8 = ((JTextField)jdate_ngaysanxuat.getDateEditor().getUiComponent()).getText();
            String value9 = txt_hamluong.getText();
            String value10 = txt_congdung.getText();
            String value11 = datetime;
            String sql = "update Medicine set ma_thuoc='"+value0+"',ten_thuoc='"+value1+"',loai_thuoc='"+value2+"',nha_san_xuat='"+value3+"',so_luong='"+value4+"',don_gia='"+value5+"',nuoc_san_xuat='"+value6+"',han_dung='"+value7+"',ngay_sx='"+value8+"',ham_luong='"+value9+"',cong_dung='"+value10+"',Time_enter='"+value11+"' where ma_thuoc='"+value0+"' ";
            
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Update success");
            
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        UpdateTableMedicine();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        MessageFormat header = new MessageFormat("Medicine List");
        MessageFormat footer = new MessageFormat("Pase{0,number,integer}");
        
        try{
            jtblist.print(JTable.PrintMode.NORMAL,header,footer);
        }catch(Exception e){
            System.err.format("Can not print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
         String sql;
        sql = "select * from Medicine order by ten_thuoc asc";
        try{
        pst= conn.prepareStatement(sql);
        rs = pst.executeQuery();
        jtblist.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showConfirmDialog(null, e);
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
      String sql = "select * from Medicine order by Time_enter asc";
        try{
        pst= conn.prepareStatement(sql);
        rs = pst.executeQuery();
        jtblist.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showConfirmDialog(null, e);
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
          String sql;
        sql = "select * from Medicine order by han_dung asc";
        try{
        pst= conn.prepareStatement(sql);
        rs = pst.executeQuery();
        jtblist.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showConfirmDialog(null, e);
        }
        
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
          String sql;
        sql = "select * from Medicine order by ngay_sx asc";
        try{
        pst= conn.prepareStatement(sql);
        rs = pst.executeQuery();
        jtblist.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showConfirmDialog(null, e);
        }
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItemSeachMaThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSeachMaThuocActionPerformed
       String str = JOptionPane.showInputDialog(this, "Nhập mã thuốc cần tìm");
        try {
            String sql = "select * from Medicine where ma_thuoc=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, str);
            rs = pst.executeQuery();
            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Có mã thuốc trong danh sách");
                String value1 = rs.getString("ma_thuoc");
                        txt_mathuoc.setText(value1);
                        String value2 = rs.getString("ten_thuoc");
                        txt_tenthuoc.setText(value2);
                        String value3 = rs.getString("loai_thuoc");
                        txt_tenloaithuoc.setText(value3);
                        String value4 = rs.getString("nha_san_xuat");
                        txt_tennhacungcap.setText(value4);
                        String value5 = rs.getString("so_luong");
                        txt_soluong.setText(value5);
                        String value6 = rs.getString("don_gia");
                        txt_dongia.setText(value6);
                        String value7 = rs.getString("nuoc_san_xuat");
                        txt_nuocsanxuat.setText(value7);
                        String value8 = rs.getString("han_dung");
                        ((JTextField)jdate_hansudung.getDateEditor().getUiComponent()).setText(value8);
                        String value9 = rs.getString("ngay_sx");
                        ((JTextField)jdate_ngaysanxuat.getDateEditor().getUiComponent()).setText(value9);
                        String value10 = rs.getString("ham_luong");
                        txt_hamluong.setText(value10);
                        String value11 = rs.getString("cong_dung");
                        txt_congdung.setText(value11);  
            } else {
                int click = JOptionPane.showConfirmDialog(null, "Không có mã thuốc cần tìm.\nBạn muốn tiếp tục tìm không ?", "Question", JOptionPane.YES_NO_OPTION);
                if(click == JOptionPane.YES_OPTION){
                    jMenuItemSeachMaThuocActionPerformed(evt);
                }
                
            }
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jMenuItemSeachMaThuocActionPerformed

    private void jMenuItemSeachTenThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSeachTenThuocActionPerformed
         String str = JOptionPane.showInputDialog(this, "Nhập tên thuốc cần tìm");
        try {
            String sql = "select * from Medicine where ten_thuoc=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, str);
            rs = pst.executeQuery();
            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Có tên thuốc trong danh sách");
                String value1 = rs.getString("ma_thuoc");
                        txt_mathuoc.setText(value1);
                        String value2 = rs.getString("ten_thuoc");
                        txt_tenthuoc.setText(value2);
                        String value3 = rs.getString("loai_thuoc");
                        txt_tenloaithuoc.setText(value3);
                        String value4 = rs.getString("nha_san_xuat");
                        txt_tennhacungcap.setText(value4);
                        String value5 = rs.getString("so_luong");
                        txt_soluong.setText(value5);
                        String value6 = rs.getString("don_gia");
                        txt_dongia.setText(value6);
                        String value7 = rs.getString("nuoc_san_xuat");
                        txt_nuocsanxuat.setText(value7);
                        String value8 = rs.getString("han_dung");
                        ((JTextField)jdate_hansudung.getDateEditor().getUiComponent()).setText(value8);
                        String value9 = rs.getString("ngay_sx");
                        ((JTextField)jdate_ngaysanxuat.getDateEditor().getUiComponent()).setText(value9);
                        String value10 = rs.getString("ham_luong");
                        txt_hamluong.setText(value10);
                        String value11 = rs.getString("cong_dung");
                        txt_congdung.setText(value11);  
            } else {
                int click = JOptionPane.showConfirmDialog(null, "Không có tên thuốc cần tìm.\nBạn muốn tiếp tục tìm không ?", "Question", JOptionPane.YES_NO_OPTION);
                if(click == JOptionPane.YES_OPTION){
                    jMenuItemSeachMaThuocActionPerformed(evt);
                }
                
            }
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jMenuItemSeachTenThuocActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
       // format truoc khi add       
            try{
                   
            String sql = "delete from Medicine2 where ma_thuoc=?";
          
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_mathuoc.getText());
            pst.execute();          
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
            
            Calendar cal = new GregorianCalendar();
            int year = cal.get(Calendar.YEAR);
            int month = cal.get(Calendar.MONTH);
            int day = cal.get(Calendar.DAY_OF_MONTH);                             
            String[] m = new String[1000];          
         
            for(int i=0;i<jtblist.getRowCount();i++)
            {
                m[i] = (String)jtblist.getModel().getValueAt(i, 7);
                String[] mangDate = m[i].split("/");
                int year2 = Integer.parseInt(mangDate[2]);               
                int month2 = Integer.parseInt(mangDate[1]);            
                int day2 = Integer.parseInt(mangDate[0]); 
                //for(int j=0;j<jtblist.getColumnCount();j++)
                //{
                //System.out.println(jtblist.getModel().getValueAt(i, j));
                //}               
                if(year2<year){
                    try {
            String sql = "Insert into Medicine2 (ma_thuoc,ten_thuoc,loai_thuoc,nha_san_xuat,so_luong,don_gia,nuoc_san_xuat,han_dung,ngay_sx,ham_luong,cong_dung) values (?,?,?,?,?,?,?,?,?,?,?)";
            pst = conn.prepareStatement(sql);            
            pst.setString(1, jtblist.getModel().getValueAt(i, 0).toString());               
                pst.setString(2, jtblist.getModel().getValueAt(i, 1).toString());
                pst.setString(3, (String)jtblist.getModel().getValueAt(i, 2));
                pst.setString(4, (String)jtblist.getModel().getValueAt(i, 3));
                pst.setString(5, (String)jtblist.getModel().getValueAt(i, 4));
                pst.setString(6, (String)jtblist.getModel().getValueAt(i, 5));
                pst.setString(7, (String)jtblist.getModel().getValueAt(i, 6));
                pst.setString(8, (String)jtblist.getModel().getValueAt(i, 7));
                pst.setString(9, (String)jtblist.getModel().getValueAt(i, 8));
                pst.setString(10, (String)jtblist.getModel().getValueAt(i,9));
                pst.setString(11, (String)jtblist.getModel().getValueAt(i, 10));
               
                pst.execute();
                pst.close();
            //JOptionPane.showMessageDialog(null, "Added!!");
            //UpdateTableMedicine();
                }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
                }
                }
               //else if(year2 == year&&month2<month){
                else if(year2 == year){
                if(month2<(month+1)){
                    try {
            String sql = "Insert into Medicine2 (ma_thuoc,ten_thuoc,loai_thuoc,nha_san_xuat,so_luong,don_gia,nuoc_san_xuat,han_dung,ngay_sx,ham_luong,cong_dung) values (?,?,?,?,?,?,?,?,?,?,?)";
            pst = conn.prepareStatement(sql);            
            pst.setString(1, jtblist.getModel().getValueAt(i, 0).toString());
                pst.setString(2, jtblist.getModel().getValueAt(i, 1).toString());
                pst.setString(3, (String)jtblist.getModel().getValueAt(i, 2));
                pst.setString(4, (String)jtblist.getModel().getValueAt(i, 3));
                pst.setString(5, (String)jtblist.getModel().getValueAt(i, 4));
                pst.setString(6, (String)jtblist.getModel().getValueAt(i, 5));
                pst.setString(7, (String)jtblist.getModel().getValueAt(i, 6));
                pst.setString(8, (String)jtblist.getModel().getValueAt(i, 7));
                pst.setString(9, (String)jtblist.getModel().getValueAt(i, 8));
                pst.setString(10, (String)jtblist.getModel().getValueAt(i,9));
                pst.setString(11, (String)jtblist.getModel().getValueAt(i, 10));
               
                pst.execute();
                pst.close();
            //JOptionPane.showMessageDialog(null, "Added!!");
            //UpdateTableMedicine();
                }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
                }
                }else if(month2 == month+1){
                if(day2<day){
                
                  try {
            String sql = "Insert into Medicine2 (ma_thuoc,ten_thuoc,loai_thuoc,nha_san_xuat,so_luong,don_gia,nuoc_san_xuat,han_dung,ngay_sx,ham_luong,cong_dung) values (?,?,?,?,?,?,?,?,?,?,?)";
            pst = conn.prepareStatement(sql);            
            pst.setString(1, jtblist.getModel().getValueAt(i, 0).toString());                       
                pst.setString(2, jtblist.getModel().getValueAt(i, 1).toString());
                pst.setString(3, (String)jtblist.getModel().getValueAt(i, 2));
                pst.setString(4, (String)jtblist.getModel().getValueAt(i, 3));
                pst.setString(5, (String)jtblist.getModel().getValueAt(i, 4));
                pst.setString(6, (String)jtblist.getModel().getValueAt(i, 5));
                pst.setString(7, (String)jtblist.getModel().getValueAt(i, 6));
                pst.setString(8, (String)jtblist.getModel().getValueAt(i, 7));
                pst.setString(9, (String)jtblist.getModel().getValueAt(i, 8));
                pst.setString(10, (String)jtblist.getModel().getValueAt(i,9));
                pst.setString(11, (String)jtblist.getModel().getValueAt(i, 10));
               
                pst.execute();
                pst.close();
            //JOptionPane.showMessageDialog(null, "Added!!");
            //UpdateTableMedicine();
                }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
                }
                }else {System.out.println("chua het han");}
                }
                 }
                
                else{
                JOptionPane.showMessageDialog(null, "Thuoc co ma "+ i+1 + " chua het han!");
                    
                }
            }
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jtblistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblistMouseClicked
        try{
             
            int row = jtblist.getSelectedRow();
            String Table_click = (jtblist.getModel().getValueAt(row, 0)).toString();
            String sql = "select * from Medicine where ma_thuoc='"+Table_click+"'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery(); 
            if(rs.next())
                    {
                        String value1 = rs.getString("ma_thuoc");
                        txt_mathuoc.setText(value1);
                        String value2 = rs.getString("ten_thuoc");
                        txt_tenthuoc.setText(value2);
                        String value3 = rs.getString("loai_thuoc");
                        txt_tenloaithuoc.setText(value3);
                        String value4 = rs.getString("nha_san_xuat");
                        txt_tennhacungcap.setText(value4);
                        String value5 = rs.getString("so_luong");
                        txt_soluong.setText(value5);
                        String value6 = rs.getString("don_gia");
                        txt_dongia.setText(value6);
                        String value7 = rs.getString("nuoc_san_xuat");
                        txt_nuocsanxuat.setText(value7);
                        String value8 = rs.getString("han_dung");
                        ((JTextField)jdate_hansudung.getDateEditor().getUiComponent()).setText(value8);
                        String value9 = rs.getString("ngay_sx");
                        ((JTextField)jdate_ngaysanxuat.getDateEditor().getUiComponent()).setText(value9);
                        String value10 = rs.getString("ham_luong");
                        txt_hamluong.setText(value10);
                        String value11 = rs.getString("cong_dung");
                        txt_congdung.setText(value11);  
                        
                    }  
            //pst.close();
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jtblistMouseClicked

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        String sql;
        sql = "select * from Medicine order by ma_thuoc asc";
        try{
        pst= conn.prepareStatement(sql);
        rs = pst.executeQuery();
        jtblist.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showConfirmDialog(null, e);
        }
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
         try{
                   
            String sql = "delete from Medicine2 where ma_thuoc=?";
          
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_mathuoc.getText());
            pst.execute();           
            JOptionPane.showMessageDialog(null, "Deleted!");
            UpdateTableMedicine();
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItemSeachMaThuoc;
    private javax.swing.JMenuItem jMenuItemSeachTenThuoc;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblist;
    private javax.swing.JTextField txt_congdung;
    private javax.swing.JTextField txt_dongia;
    private javax.swing.JTextField txt_hamluong;
    private javax.swing.JTextField txt_mathuoc;
    private javax.swing.JTextField txt_nuocsanxuat;
    private javax.swing.JTextField txt_soluong;
    private javax.swing.JTextField txt_tenloaithuoc;
    private javax.swing.JTextField txt_tennhacungcap;
    private javax.swing.JTextField txt_tenthuoc;
    // End of variables declaration//GEN-END:variables
}
