/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_management;

import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Tài
 */
public class TaiKhoanAdmin extends javax.swing.JInternalFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    String userName = Login.useNameLogin;
    String passWord = Login.passWordLogin;

    /**
     * Creates new form ThongKe
     */
    public TaiKhoanAdmin() {
        initComponents();
        conn = JavaConnect.ConnectDB();
        //set name to text field tai khoan
        lbTaiKhoan.setText(userName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTaiKhoan = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pFMatKhauCu = new javax.swing.JPasswordField();
        pFMatKhauMoi = new javax.swing.JPasswordField();
        pFMatKhauNhapLai = new javax.swing.JPasswordField();
        lbTaiKhoan = new javax.swing.JLabel();
        btnTaiKhoanLuu = new javax.swing.JButton();
        btnTaiKHoanHuy = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButtonAdmin = new javax.swing.JRadioButton();
        btnHuyTaoTaiKhoan = new javax.swing.JButton();
        btnTaoTaiKhoan = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtTaoTenDangNhap = new javax.swing.JTextField();
        jRadioButtonBinhThuong = new javax.swing.JRadioButton();
        jPasswordTaoTaiKhoan = new javax.swing.JPasswordField();
        jPasswordFieldTaoTaiKhoanAgain = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setTitle("Tài khoản");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Đổi mật khẩu", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.setToolTipText("");
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.setName(""); // NOI18N

        jLabel1.setText("Tài khoản :");

        jLabel3.setText("Mật khẩu mới :");

        jLabel2.setText("Mật khẩu cũ :");

        jLabel4.setText("Nhập lại mật khẩu mới :");

        lbTaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbTaiKhoan.setForeground(new java.awt.Color(0, 0, 153));

        btnTaiKhoanLuu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTaiKhoanLuu.setForeground(new java.awt.Color(0, 0, 153));
        btnTaiKhoanLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/45.png"))); // NOI18N
        btnTaiKhoanLuu.setText("Lưu");
        btnTaiKhoanLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaiKhoanLuuActionPerformed(evt);
            }
        });

        btnTaiKHoanHuy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTaiKHoanHuy.setForeground(new java.awt.Color(153, 0, 0));
        btnTaiKHoanHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Remove.png"))); // NOI18N
        btnTaiKHoanHuy.setText("Hủy");
        btnTaiKHoanHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaiKHoanHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pFMatKhauCu, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(pFMatKhauMoi)
                    .addComponent(pFMatKhauNhapLai)
                    .addComponent(lbTaiKhoan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTaiKhoanLuu)
                .addGap(67, 67, 67)
                .addComponent(btnTaiKHoanHuy)
                .addGap(78, 78, 78))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pFMatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pFMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pFMatKhauNhapLai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTaiKhoanLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTaiKHoanHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tạo tài khoản", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(51, 0, 204))); // NOI18N

        jLabel9.setText("Nhập lại mật khẩu");

        jLabel7.setText("Tên đăng nhập");

        buttonGroupTaiKhoan.add(jRadioButtonAdmin);
        jRadioButtonAdmin.setText("Admin");

        btnHuyTaoTaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHuyTaoTaiKhoan.setForeground(new java.awt.Color(204, 0, 0));
        btnHuyTaoTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Remove.png"))); // NOI18N
        btnHuyTaoTaiKhoan.setText("Hủy");
        btnHuyTaoTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyTaoTaiKhoanActionPerformed(evt);
            }
        });

        btnTaoTaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTaoTaiKhoan.setForeground(new java.awt.Color(0, 102, 0));
        btnTaoTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add.png"))); // NOI18N
        btnTaoTaiKhoan.setText("Tạo");
        btnTaoTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoTaiKhoanActionPerformed(evt);
            }
        });

        jLabel8.setText("Mật khẩu");

        buttonGroupTaiKhoan.add(jRadioButtonBinhThuong);
        jRadioButtonBinhThuong.setText("Bình thường");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordTaoTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(txtTaoTenDangNhap)
                            .addComponent(jPasswordFieldTaoTaiKhoanAgain)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTaoTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButtonAdmin)
                                .addGap(40, 40, 40)
                                .addComponent(jRadioButtonBinhThuong)))
                        .addGap(4, 6, Short.MAX_VALUE)
                        .addComponent(btnHuyTaoTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTaoTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jPasswordTaoTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jPasswordFieldTaoTaiKhoanAgain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonAdmin)
                    .addComponent(jRadioButtonBinhThuong))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHuyTaoTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTaoTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/userChangePassword.png"))); // NOI18N
        jLabel5.setToolTipText("");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/User-Groupss.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/MeasureList.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(162, 162, 162)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaiKhoanLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaiKhoanLuuActionPerformed
        String tk = lbTaiKhoan.getText();
        String matKhauCu = pFMatKhauCu.getText();
        String matKhauMoi = pFMatKhauMoi.getText();
        String matKhauMoiAgain = pFMatKhauNhapLai.getText();
        if (tk.equals(userName) && matKhauCu.equals(passWord)) {
            if ((matKhauMoi != null) && (matKhauMoiAgain != null)) {
                if (!matKhauCu.equals(matKhauMoi)) {
                    if (matKhauMoi.equals(matKhauMoiAgain)) {
                        try {
                            String sql = "update login set usename='" + tk + "',password='" + matKhauMoi + "' where usename='" + tk + "' ";
                            pst = conn.prepareStatement(sql);
                            pst.execute();
                            JOptionPane.showMessageDialog(null, "Đổi mật khẩu thành công");
                            pst.close();
                            rs.close();
                        } catch (SQLException e) {
                            JOptionPane.showMessageDialog(null, e);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Nhập lại mật khẩu mới không đúng");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Mật khẩu mới trùng mật khẩu cũ");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Mật khẩu mới bị trống");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Mật khẩu cũ không đúng");
        }

    }//GEN-LAST:event_btnTaiKhoanLuuActionPerformed

    private void btnTaiKHoanHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaiKHoanHuyActionPerformed
        pFMatKhauCu.setText("");
        pFMatKhauMoi.setText("");
        pFMatKhauNhapLai.setText("");
    }//GEN-LAST:event_btnTaiKHoanHuyActionPerformed

    private void btnHuyTaoTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyTaoTaiKhoanActionPerformed
        txtTaoTenDangNhap.setText("");
        jPasswordTaoTaiKhoan.setText("");
        jPasswordFieldTaoTaiKhoanAgain.setText("");
    }//GEN-LAST:event_btnHuyTaoTaiKhoanActionPerformed

    private void btnTaoTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoTaiKhoanActionPerformed
        String user = txtTaoTenDangNhap.getText();
        String password = jPasswordTaoTaiKhoan.getText();
        String passwordAgain = jPasswordFieldTaoTaiKhoanAgain.getText();
        int admin = 0;
        if (jRadioButtonAdmin.isSelected()) {
            admin = 1;
        }

        String sql = "select * from login where usename=?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, user);
            rs = pst.executeQuery();
            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Tên đăng nhập đã tồn tại\nHãy chọn lại tên đăng nhập");
            } else {
                if (user.isEmpty() | password.isEmpty() | passwordAgain.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Nhập tên đăng nhập và mật khẩu !");
                } else {
                    if (!(jRadioButtonBinhThuong.isSelected() | jRadioButtonAdmin.isSelected())) {
                        JOptionPane.showMessageDialog(null, "Chọn loại tài khoản !");
                    } else {
                        if (password.equals(passwordAgain)) {
                            themTaiKhoan(user, password, admin);
                        } else {
                            JOptionPane.showMessageDialog(null, "Mật khẩu không khớp");
                        }
                    }
                }
            }

        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnTaoTaiKhoanActionPerformed

    private void themTaiKhoan(String use, String pass, int admin) {
        String sql = "Insert into login(usename,password,admin) values (?,?,?)";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, use);
            pst.setString(2, pass);
            pst.setInt(3, admin);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Thêm tài khoản thành công");
            pst.close();
            rs.close();
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuyTaoTaiKhoan;
    private javax.swing.JButton btnTaiKHoanHuy;
    private javax.swing.JButton btnTaiKhoanLuu;
    private javax.swing.JButton btnTaoTaiKhoan;
    private javax.swing.ButtonGroup buttonGroupTaiKhoan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordFieldTaoTaiKhoanAgain;
    private javax.swing.JPasswordField jPasswordTaoTaiKhoan;
    private javax.swing.JRadioButton jRadioButtonAdmin;
    private javax.swing.JRadioButton jRadioButtonBinhThuong;
    private javax.swing.JLabel lbTaiKhoan;
    private javax.swing.JPasswordField pFMatKhauCu;
    private javax.swing.JPasswordField pFMatKhauMoi;
    private javax.swing.JPasswordField pFMatKhauNhapLai;
    private javax.swing.JTextField txtTaoTenDangNhap;
    // End of variables declaration//GEN-END:variables
}
