/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_management;

import java.awt.HeadlessException;
import java.awt.event.ItemEvent;
import java.sql.*;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
import org.sqlite.SQLite;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.awt.event.KeyEvent;
import java.time.Instant;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.TimeZone;

/**
 *
 * @author Tài
 */
public class Thuoc extends javax.swing.JInternalFrame {

    Connection connThuoc = null;
    Connection conn = null;
    ResultSet rsThuoc = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    PreparedStatement pstThuoc = null;

    /**
     * Creates new form Thuoc
     */
    public Thuoc() {
        initComponents();
        connThuoc = JavaConnect.ConnectDB();
        updateTableThuoc();
        formatHistory();
    }

    // xóa lịch sử
    private void formatHistory() {
        Calendar cal = new GregorianCalendar();

        int month = cal.get(Calendar.MONTH);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        if (day == 30 && month == 6) {
            try {
                String sql = "delete from TableThuoc";

                pstThuoc = connThuoc.prepareStatement(sql);
                pstThuoc.execute();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }

    //update table thuoc
    private void updateTableThuoc() {

        String sql = "select * from TableThuoc";
        try {
            pstThuoc = connThuoc.prepareStatement(sql);
            rsThuoc = pstThuoc.executeQuery();
            jTableThuoc.setModel(DbUtils.resultSetToTableModel(rsThuoc));
            pstThuoc.close();
            rsThuoc.close();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTenThuoc = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        txtNuocSanXuat = new javax.swing.JTextField();
        txtMaThuoc = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        txtNhaCungCap = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaCongDung = new javax.swing.JTextArea();
        txtSTT = new javax.swing.JTextField();
        jDateChooserHanSuDung = new com.toedter.calendar.JDateChooser();
        jDateChooserNgaySanXuat = new com.toedter.calendar.JDateChooser();
        jPanel6 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableThuoc = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnPrintThuoc = new javax.swing.JButton();
        btnSuaThuoc = new javax.swing.JButton();
        btnXoaThuoc = new javax.swing.JButton();
        btnThemThuoc = new javax.swing.JButton();
        btnSapXepTen = new javax.swing.JButton();
        btnSapXepNgaySX = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnSapXepHSD = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnSapXepSTT = new javax.swing.JButton();

        setTitle("Quản lý thuốc");

        txtTenThuoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTenThuocKeyReleased(evt);
            }
        });

        txtNuocSanXuat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNuocSanXuatKeyReleased(evt);
            }
        });

        txtMaThuoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMaThuocKeyReleased(evt);
            }
        });

        txtNhaCungCap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNhaCungCapKeyReleased(evt);
            }
        });

        txtAreaCongDung.setColumns(20);
        txtAreaCongDung.setRows(5);
        jScrollPane1.setViewportView(txtAreaCongDung);

        jDateChooserHanSuDung.setDateFormatString("dd/MM/yyyy");

        jDateChooserNgaySanXuat.setDateFormatString("dd/MM/yyyy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaThuoc, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTenThuoc, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNhaCungCap, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNuocSanXuat, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(txtSTT)
                    .addComponent(jDateChooserNgaySanXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooserHanSuDung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtSTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtMaThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTenThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNuocSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jDateChooserHanSuDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jDateChooserNgaySanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel37.setText("Tên thuốc");

        jLabel38.setText("Mã thuốc");

        jLabel39.setText("Số lượng");

        jLabel40.setText("Nước sản xuất");

        jLabel41.setText("Đơn giá");

        jLabel42.setText("Ngày Sản xuất");

        jLabel43.setText("Nhà cung cấp");

        jLabel44.setText("Hạn sử dụng");

        jLabel45.setText("Công dụng");

        jLabel2.setText("STT");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel45)
                    .addComponent(jLabel42)
                    .addComponent(jLabel44)
                    .addComponent(jLabel37)
                    .addComponent(jLabel43)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39)
                    .addComponent(jLabel41)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addGap(11, 11, 11))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(jLabel38)
                .addGap(27, 27, 27)
                .addComponent(jLabel37)
                .addGap(32, 32, 32)
                .addComponent(jLabel43)
                .addGap(28, 28, 28)
                .addComponent(jLabel39)
                .addGap(29, 29, 29)
                .addComponent(jLabel41)
                .addGap(30, 30, 30)
                .addComponent(jLabel40)
                .addGap(28, 28, 28)
                .addComponent(jLabel44)
                .addGap(27, 27, 27)
                .addComponent(jLabel42)
                .addGap(31, 31, 31)
                .addComponent(jLabel45)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableThuoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã thuốc", "Tên thuốc", "Nhà cung cấp", "Số lượng", "Đơn giá", "Nước sản xuất", "Hạn sử dụng", "Ngày sản xuất", "Công dụng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableThuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableThuocMouseClicked(evt);
            }
        });
        jTableThuoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableThuocKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTableThuoc);
        if (jTableThuoc.getColumnModel().getColumnCount() > 0) {
            jTableThuoc.getColumnModel().getColumn(0).setPreferredWidth(25);
            jTableThuoc.getColumnModel().getColumn(9).setPreferredWidth(100);
        }

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "HÀNH ĐỘNG", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(51, 0, 153))); // NOI18N

        btnPrintThuoc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPrintThuoc.setForeground(new java.awt.Color(255, 0, 102));
        btnPrintThuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/print16x16.png"))); // NOI18N
        btnPrintThuoc.setText("In");
        btnPrintThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintThuocActionPerformed(evt);
            }
        });

        btnSuaThuoc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSuaThuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/fix16x16.png"))); // NOI18N
        btnSuaThuoc.setText("Sửa");
        btnSuaThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaThuocActionPerformed(evt);
            }
        });

        btnXoaThuoc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoaThuoc.setForeground(new java.awt.Color(255, 0, 0));
        btnXoaThuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/exit16x16.png"))); // NOI18N
        btnXoaThuoc.setText("Xóa");
        btnXoaThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaThuocActionPerformed(evt);
            }
        });

        btnThemThuoc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThemThuoc.setForeground(new java.awt.Color(0, 153, 0));
        btnThemThuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add16x16.png"))); // NOI18N
        btnThemThuoc.setText("Thêm");
        btnThemThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemThuocActionPerformed(evt);
            }
        });

        btnSapXepTen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSapXepTen.setForeground(new java.awt.Color(0, 153, 0));
        btnSapXepTen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/SapXep16x16.png"))); // NOI18N
        btnSapXepTen.setText("Sắp xếp tên");
        btnSapXepTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapXepTenActionPerformed(evt);
            }
        });

        btnSapXepNgaySX.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSapXepNgaySX.setForeground(new java.awt.Color(153, 0, 153));
        btnSapXepNgaySX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/SapXep16x16.png"))); // NOI18N
        btnSapXepNgaySX.setText("Sắp xếp Ngày SX");
        btnSapXepNgaySX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapXepNgaySXActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/taoList16x16.png"))); // NOI18N
        jButton1.setText("Tạo danh sách thuốc hết hạn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 0, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/list16x16.png"))); // NOI18N
        jButton2.setText("Danh sách thuốc hết hạn");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/send16x16.png"))); // NOI18N
        jButton3.setText("Gửi thông tin");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnSapXepHSD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSapXepHSD.setForeground(new java.awt.Color(51, 51, 255));
        btnSapXepHSD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/SapXep16x16.png"))); // NOI18N
        btnSapXepHSD.setText("Sắp xếp theo HSD");
        btnSapXepHSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapXepHSDActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/refesh16x16.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnSapXepSTT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSapXepSTT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/SapXep16x16.png"))); // NOI18N
        btnSapXepSTT.setText("Sắp xếp theo STT");
        btnSapXepSTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapXepSTTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(35, 35, 35))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnThemThuoc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSuaThuoc)
                                .addGap(48, 48, 48)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addComponent(jButton3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(btnXoaThuoc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnPrintThuoc))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(btnSapXepHSD)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSapXepSTT)
                                    .addComponent(btnReset, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSapXepTen)
                        .addGap(18, 18, 18)
                        .addComponent(btnSapXepNgaySX)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemThuoc)
                    .addComponent(btnReset)
                    .addComponent(btnPrintThuoc)
                    .addComponent(btnXoaThuoc)
                    .addComponent(btnSuaThuoc))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSapXepNgaySX)
                    .addComponent(btnSapXepHSD)
                    .addComponent(btnSapXepTen)
                    .addComponent(btnSapXepSTT))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableThuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableThuocMouseClicked
        // TODO add your handling code here:
        try {
            int row = jTableThuoc.getSelectedRow();
            String tableClick = (jTableThuoc.getModel().getValueAt(row, 0).toString());
            String sql = "Select * from TableThuoc where STT='" + tableClick + "' ";
            pstThuoc = connThuoc.prepareStatement(sql);
            rsThuoc = pstThuoc.executeQuery();
            if (rsThuoc.next()) {
                String add0 = rsThuoc.getString("STT");
                txtSTT.setText(add0);
                String add1 = rsThuoc.getString("MaThuoc");
                txtMaThuoc.setText(add1);
                String add2 = rsThuoc.getString("TenThuoc");
                txtTenThuoc.setText(add2);

                String add3 = rsThuoc.getString("NhaCungCap");
                txtNhaCungCap.setText(add3);
                String add4 = rsThuoc.getString("SoLuong");
                txtSoLuong.setText(add4);

                String add5 = rsThuoc.getString("DonGia");
                txtDonGia.setText(add5);
                String add6 = rsThuoc.getString("NuocSanXuat");
                txtNuocSanXuat.setText(add6);

                String add7 = rsThuoc.getString("HanSuDung");
                Date date1 = new SimpleDateFormat("dd/MM/yyyy").parse(add7);
                jDateChooserHanSuDung.setDate(date1);
                String add8 = rsThuoc.getString("NgaySanXuat");
                Date date2 = new SimpleDateFormat("dd/MM/yyyy").parse(add8);
                jDateChooserNgaySanXuat.setDate(date2);

                String add9 = rsThuoc.getString("CongDung");
                txtAreaCongDung.setText(add9);
                pstThuoc.close();
                rsThuoc.close();
            }

        } catch (SQLException | ParseException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jTableThuocMouseClicked

    private void btnThemThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemThuocActionPerformed
        // TODO add your handling code here:
        try {

            String sql = "Insert into TableThuoc(STT,MaThuoc,TenThuoc,NhaCungCap,SoLuong,DonGia,NuocSanXuat,HanSuDung,NgaySanXuat,CongDung) values (?,?,?,?,?,?,?,?,?,?)";

            // + "Nhà cung cấp,Số lượng,Đơn giá,Nước sản xuất,Hạn sử dụng,Ngày sản xuất,Công dụng) "
            //  + "values (?,?,?,?,?,?,?,?,?,?)";
            pstThuoc = connThuoc.prepareStatement(sql);
            pstThuoc.setString(1, txtSTT.getText());

            pstThuoc.setString(2, txtMaThuoc.getText());
            pstThuoc.setString(3, txtTenThuoc.getText());

            pstThuoc.setString(4, txtNhaCungCap.getText());
            pstThuoc.setString(5, txtSoLuong.getText());

            pstThuoc.setString(6, txtDonGia.getText());
            pstThuoc.setString(7, txtNuocSanXuat.getText());

            pstThuoc.setString(8, ((JTextField) jDateChooserHanSuDung.getDateEditor().getUiComponent()).getText());
            pstThuoc.setString(9, ((JTextField) jDateChooserNgaySanXuat.getDateEditor().getUiComponent()).getText());

            pstThuoc.setString(10, txtAreaCongDung.getText());

            pstThuoc.execute();
            pstThuoc.close();
            rsThuoc.close();
            JOptionPane.showMessageDialog(null, "Lưu thành công");

        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        updateTableThuoc();
    }//GEN-LAST:event_btnThemThuocActionPerformed

    private void btnXoaThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaThuocActionPerformed
        int p = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa", "Xóa", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            String sql = "delete from TableThuoc where STT =?";
            try {
                pstThuoc = connThuoc.prepareStatement(sql);
                pstThuoc.setString(1, txtSTT.getText());
                pstThuoc.execute();
                JOptionPane.showMessageDialog(null, "Xóa thành công");
                pstThuoc.close();
                rsThuoc.close();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            updateTableThuoc();
    }//GEN-LAST:event_btnXoaThuocActionPerformed
    }
    private void btnSuaThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaThuocActionPerformed
        // TODO add your handling code here:
        try {
            // String value10 = txtSTT.getText();
            String value0 = txtSTT.getText();
            String value1 = txtMaThuoc.getText();
            String value2 = txtTenThuoc.getText();
            String value3 = txtNhaCungCap.getText();
            String value4 = txtSoLuong.getText();
            String value5 = txtDonGia.getText();
            String value6 = txtNuocSanXuat.getText();
            String value7 = ((JTextField) jDateChooserHanSuDung.getDateEditor().getUiComponent()).getText();
            String value8 = ((JTextField) jDateChooserNgaySanXuat.getDateEditor().getUiComponent()).getText();
            String value9 = txtAreaCongDung.getText();

            String sql = "update TableThuoc set STT='" + value0 + "',MaThuoc='" + value1 + "',TenThuoc='" + value2 + "',NhaCungCap='" + value3 + "',SoLuong='" + value4 + "',DonGia='" + value5 + "',NuocSanXuat='" + value6 + "',HanSuDung='" + value7 + "',NgaySanXuat='" + value8 + "',CongDung='" + value9 + "' where STT='" + value0 + "' ";

            pstThuoc = connThuoc.prepareStatement(sql);
            pstThuoc.execute();
            JOptionPane.showMessageDialog(null, "Sửa thành công");
            pstThuoc.close();
            rsThuoc.close();

        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        updateTableThuoc();
    }//GEN-LAST:event_btnSuaThuocActionPerformed

    private void btnPrintThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintThuocActionPerformed
        MessageFormat header = new MessageFormat("Danh sách thuốc");
        MessageFormat footer = new MessageFormat("Pase{0,number,integer}");

        try {
            jTableThuoc.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (Exception e) {
            System.err.format("Không thể in %s%n", e.getMessage());
        }
    }//GEN-LAST:event_btnPrintThuocActionPerformed

    private void btnSapXepTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapXepTenActionPerformed
        // SQLite> Select from TableThuoc order by TenThuoc asc;
        //  SQLite > SELECT * FROM TableThuoc ORDER BY TenThuoc ASC;
        String sql = "select * from TableThuoc order by TenThuoc asc";
        try {
            pstThuoc = connThuoc.prepareStatement(sql);
            rsThuoc = pstThuoc.executeQuery();
            jTableThuoc.setModel(DbUtils.resultSetToTableModel(rsThuoc));
            pstThuoc.close();
            rsThuoc.close();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }//GEN-LAST:event_btnSapXepTenActionPerformed

    private void btnSapXepNgaySXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapXepNgaySXActionPerformed
        // TODO add your handling code here:
        String sql = "select * from TableThuoc order by NgaySanXuat asc";
        try {
            pstThuoc = connThuoc.prepareStatement(sql);
            rsThuoc = pstThuoc.executeQuery();
            jTableThuoc.setModel(DbUtils.resultSetToTableModel(rsThuoc));
            pstThuoc.close();
            rsThuoc.close();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
    }//GEN-LAST:event_btnSapXepNgaySXActionPerformed
    }
    private void txtMaThuocKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaThuocKeyReleased
        TextAutoCompleter autoMaThuoc = new TextAutoCompleter(txtMaThuoc);

        try {

            String sql = "Select * from TableThuoc";
            pstThuoc = connThuoc.prepareStatement(sql);
            rsThuoc = pstThuoc.executeQuery();
            while (rsThuoc.next()) {
                String maThuoc = rsThuoc.getString("MaThuoc");
                autoMaThuoc.addItem(maThuoc);
                pstThuoc.close();
                rsThuoc.close();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_txtMaThuocKeyReleased

    private void txtTenThuocKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenThuocKeyReleased

        TextAutoCompleter autoTenThuoc = new TextAutoCompleter(txtTenThuoc);

        try {

            String sql = "Select * from TableThuoc";
            pstThuoc = connThuoc.prepareStatement(sql);
            rsThuoc = pstThuoc.executeQuery();
            while (rsThuoc.next()) {

                String tenThuoc = rsThuoc.getString("TenThuoc");
                autoTenThuoc.addItem(tenThuoc);
                pstThuoc.close();
                rsThuoc.close();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_txtTenThuocKeyReleased

    private void txtNhaCungCapKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNhaCungCapKeyReleased
        TextAutoCompleter autoNhaCungCap = new TextAutoCompleter(txtNhaCungCap);

        try {

            String sql = "Select * from TableThuoc";
            pstThuoc = connThuoc.prepareStatement(sql);
            rsThuoc = pstThuoc.executeQuery();
            while (rsThuoc.next()) {
                String nhaCungCap = rsThuoc.getString("NhaCungCap");
                autoNhaCungCap.addItem(nhaCungCap);
                pstThuoc.close();
                rsThuoc.close();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_txtNhaCungCapKeyReleased

    private void txtNuocSanXuatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNuocSanXuatKeyReleased
        TextAutoCompleter autoNuocSanXuat = new TextAutoCompleter(txtNuocSanXuat);

        try {
            String sql = "Select * from TableThuoc";
            pstThuoc = connThuoc.prepareStatement(sql);
            rsThuoc = pstThuoc.executeQuery();
            while (rsThuoc.next()) {

                String nuocSanXuat = rsThuoc.getString("NuocSanXuat");
                autoNuocSanXuat.addItem(nuocSanXuat);
                pstThuoc.close();
                rsThuoc.close();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_txtNuocSanXuatKeyReleased

    private void jTableThuocKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableThuocKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP) {
            try {
                int row = jTableThuoc.getSelectedRow();
                String tableClick = (jTableThuoc.getModel().getValueAt(row, 0).toString());
                String sql = "Select * from TableThuoc where STT='" + tableClick + "' ";
                pstThuoc = connThuoc.prepareStatement(sql);
                rsThuoc = pstThuoc.executeQuery();
                if (rsThuoc.next()) {
                    String add0 = rsThuoc.getString("STT");
                    txtSTT.setText(add0);
                    String add1 = rsThuoc.getString("MaThuoc");
                    txtMaThuoc.setText(add1);
                    String add2 = rsThuoc.getString("TenThuoc");
                    txtTenThuoc.setText(add2);

                    String add3 = rsThuoc.getString("NhaCungCap");
                    txtNhaCungCap.setText(add3);
                    String add4 = rsThuoc.getString("SoLuong");
                    txtSoLuong.setText(add4);

                    String add5 = rsThuoc.getString("DonGia");
                    txtDonGia.setText(add5);
                    String add6 = rsThuoc.getString("NuocSanXuat");
                    txtNuocSanXuat.setText(add6);

                    String add7 = rsThuoc.getString("HanSuDung");
                    Date date1 = new SimpleDateFormat("dd/MM/yyyy").parse(add7);
                    jDateChooserHanSuDung.setDate(date1);
                    String add8 = rsThuoc.getString("NgaySanXuat");
                    Date date2 = new SimpleDateFormat("dd/MM/yyyy").parse(add8);
                    jDateChooserNgaySanXuat.setDate(date2);

                    String add9 = rsThuoc.getString("CongDung");
                    txtAreaCongDung.setText(add9);
                    pstThuoc.close();
                    rsThuoc.close();
                }

            } catch (SQLException | ParseException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jTableThuocKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // format truoc khi add       
        try {

            String sql = "delete from Medicine2";

            pstThuoc = connThuoc.prepareStatement(sql);
            pstThuoc.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        Calendar cal = new GregorianCalendar();
        int year = cal.get(Calendar.YEAR);
        int month = cal.get(Calendar.MONTH);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        String[] m = new String[1000];

        for (int i = 0; i < jTableThuoc.getRowCount(); i++) {
            m[i] = (String) jTableThuoc.getModel().getValueAt(i, 7);
            String[] mangDate = m[i].split("/");
            int year2 = Integer.parseInt(mangDate[2]);
            int month2 = Integer.parseInt(mangDate[1]);
            int day2 = Integer.parseInt(mangDate[0]);

            if (year2 < year) {
                try {
                    String sql = "Insert into Medicine2 (STT,MaThuoc,TenThuoc,NhaCungCap,SoLuong,DonGia,NuocSanXuat,HanSuDung,NgaySanXuat,CongDung) values (?,?,?,?,?,?,?,?,?,?)";
                    pstThuoc = connThuoc.prepareStatement(sql);
                    pstThuoc.setString(1, jTableThuoc.getModel().getValueAt(i, 0).toString());
                    pstThuoc.setString(2, jTableThuoc.getModel().getValueAt(i, 1).toString());
                    pstThuoc.setString(3, jTableThuoc.getModel().getValueAt(i, 2).toString());
                    pstThuoc.setString(4, jTableThuoc.getModel().getValueAt(i, 3).toString());
                    pstThuoc.setString(5, jTableThuoc.getModel().getValueAt(i, 4).toString());
                    pstThuoc.setString(6, jTableThuoc.getModel().getValueAt(i, 5).toString());
                    pstThuoc.setString(7, jTableThuoc.getModel().getValueAt(i, 6).toString());
                    pstThuoc.setString(8, jTableThuoc.getModel().getValueAt(i, 7).toString());
                    pstThuoc.setString(9, jTableThuoc.getModel().getValueAt(i, 8).toString());
                    pstThuoc.setString(10, jTableThuoc.getModel().getValueAt(i, 9).toString());

                    pstThuoc.execute();
                    pstThuoc.close();
                    rsThuoc.close();
                    //JOptionPane.showMessageDialog(null, "Danh sách thuốc hết hạn đã được tạo !");
                    //UpdateTableMedicine();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            } //else if(year2 == year&&month2<month){
            else if (year2 == year) {
                if (month2 < (month + 1)) {
                    try {
                        String sql = "Insert into Medicine2 (STT,MaThuoc,TenThuoc,NhaCungCap,SoLuong,DonGia,NuocSanXuat,HanSuDung,NgaySanXuat,CongDung) values (?,?,?,?,?,?,?,?,?,?)";
                        pstThuoc = connThuoc.prepareStatement(sql);
                        pstThuoc.setString(1, jTableThuoc.getModel().getValueAt(i, 0).toString());
                        pstThuoc.setString(2, jTableThuoc.getModel().getValueAt(i, 1).toString());
                        pstThuoc.setString(3, jTableThuoc.getModel().getValueAt(i, 2).toString());
                        pstThuoc.setString(4, jTableThuoc.getModel().getValueAt(i, 3).toString());
                        pstThuoc.setString(5, jTableThuoc.getModel().getValueAt(i, 4).toString());
                        pstThuoc.setString(6, jTableThuoc.getModel().getValueAt(i, 5).toString());
                        pstThuoc.setString(7, jTableThuoc.getModel().getValueAt(i, 6).toString());
                        pstThuoc.setString(8, jTableThuoc.getModel().getValueAt(i, 7).toString());
                        pstThuoc.setString(9, jTableThuoc.getModel().getValueAt(i, 8).toString());
                        pstThuoc.setString(10, jTableThuoc.getModel().getValueAt(i, 9).toString());
                        pstThuoc.execute();
                        pstThuoc.close();
                        rsThuoc.close();
                        //JOptionPane.showMessageDialog(null, "Danh sách thuốc hết hạn đã được tạo !");
                        //UpdateTableMedicine();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                } else if (month2 == month + 1) {
                    if (day2 < day) {

                        try {
                            String sql = "Insert into Medicine2 (STT,MaThuoc,TenThuoc,NhaCungCap,SoLuong,DonGia,NuocSanXuat,HanSuDung,NgaySanXuat,CongDung) values (?,?,?,?,?,?,?,?,?,?)";
                            pstThuoc = connThuoc.prepareStatement(sql);
                            pstThuoc.setString(1, jTableThuoc.getModel().getValueAt(i, 0).toString());
                            pstThuoc.setString(2, jTableThuoc.getModel().getValueAt(i, 1).toString());
                            pstThuoc.setString(3, jTableThuoc.getModel().getValueAt(i, 2).toString());
                            pstThuoc.setString(4, jTableThuoc.getModel().getValueAt(i, 3).toString());
                            pstThuoc.setString(5, jTableThuoc.getModel().getValueAt(i, 4).toString());
                            pstThuoc.setString(6, jTableThuoc.getModel().getValueAt(i, 5).toString());
                            pstThuoc.setString(7, jTableThuoc.getModel().getValueAt(i, 6).toString());
                            pstThuoc.setString(8, jTableThuoc.getModel().getValueAt(i, 7).toString());
                            pstThuoc.setString(9, jTableThuoc.getModel().getValueAt(i, 8).toString());
                            pstThuoc.setString(10, jTableThuoc.getModel().getValueAt(i, 9).toString());
                            pstThuoc.execute();
                            pstThuoc.close();
                            rsThuoc.close();
                            //JOptionPane.showMessageDialog(null, "Danh sách thuốc hết hạn đã được tạo !");
                            //UpdateTableMedicine();
                        } catch (SQLException | HeadlessException e) {
                            JOptionPane.showMessageDialog(null, e);
                        }
                    } else {
                        System.out.println("chua het han");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Thuoc co ma " + i + 1 + " chua het han!");

            }
        }
        JOptionPane.showMessageDialog(null, "Danh sách thuốc hết hạn đã được tạo !");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        List_Thuoc_Het_Han list = new List_Thuoc_Het_Han();
        list.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        GuiThongTin tt = new GuiThongTin();
        tt.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed

        txtSTT.setText("");
        txtMaThuoc.setText("");
        txtTenThuoc.setText("");
        txtNhaCungCap.setText("");
        txtSoLuong.setText("");
        txtDonGia.setText("");
        txtNuocSanXuat.setText("");
        jDateChooserHanSuDung.setDate(null);
        jDateChooserNgaySanXuat.setDate(null);
        txtAreaCongDung.setText("");
/*
        String sql = "select * from TableThuoc where HanSuDung between 12/02/2015 and 12/04/2015 insert into Medicine2";
         try {
            pst = conn.prepareStatement(sql);        
           
            pstThuoc.execute();
               // pst.close();
                //rs.close();
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        */
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSapXepHSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapXepHSDActionPerformed
        String sql = "select * from TableThuoc order by HanSuDung asc";
        try {
            pstThuoc = connThuoc.prepareStatement(sql);
            rsThuoc = pstThuoc.executeQuery();
            jTableThuoc.setModel(DbUtils.resultSetToTableModel(rsThuoc));
            pstThuoc.close();
            rsThuoc.close();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }//GEN-LAST:event_btnSapXepHSDActionPerformed

    private void btnSapXepSTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapXepSTTActionPerformed
        String sql = "select * from TableThuoc order by STT asc";
        try {
            pstThuoc = connThuoc.prepareStatement(sql);
            rsThuoc = pstThuoc.executeQuery();
            jTableThuoc.setModel(DbUtils.resultSetToTableModel(rsThuoc));
            pstThuoc.close();
            rsThuoc.close();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }//GEN-LAST:event_btnSapXepSTTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrintThuoc;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSapXepHSD;
    private javax.swing.JButton btnSapXepNgaySX;
    private javax.swing.JButton btnSapXepSTT;
    private javax.swing.JButton btnSapXepTen;
    private javax.swing.JButton btnSuaThuoc;
    private javax.swing.JButton btnThemThuoc;
    private javax.swing.JButton btnXoaThuoc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooserHanSuDung;
    private com.toedter.calendar.JDateChooser jDateChooserNgaySanXuat;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableThuoc;
    private javax.swing.JTextArea txtAreaCongDung;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaThuoc;
    private javax.swing.JTextField txtNhaCungCap;
    private javax.swing.JTextField txtNuocSanXuat;
    private javax.swing.JTextField txtSTT;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenThuoc;
    // End of variables declaration//GEN-END:variables
}
